// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: albums.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAlbum = `-- name: CreateAlbum :one
INSERT INTO albums (name, name_normalized, release_date) VALUES ($1, $2, $3) RETURNING id, name, name_normalized, release_date, description, image_id, pinned, created_at, updated_at
`

type CreateAlbumParams struct {
	Name           string      `json:"name"`
	NameNormalized string      `json:"name_normalized"`
	ReleaseDate    pgtype.Date `json:"release_date"`
}

func (q *Queries) CreateAlbum(ctx context.Context, arg CreateAlbumParams) (Album, error) {
	row := q.db.QueryRow(ctx, createAlbum, arg.Name, arg.NameNormalized, arg.ReleaseDate)
	var i Album
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameNormalized,
		&i.ReleaseDate,
		&i.Description,
		&i.ImageID,
		&i.Pinned,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAlbum = `-- name: DeleteAlbum :execrows
DELETE FROM albums WHERE id = $1
`

func (q *Queries) DeleteAlbum(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAlbum, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteAlbumArtists = `-- name: DeleteAlbumArtists :exec
DELETE FROM album_artists WHERE album_id = $1
`

func (q *Queries) DeleteAlbumArtists(ctx context.Context, albumID int64) error {
	_, err := q.db.Exec(ctx, deleteAlbumArtists, albumID)
	return err
}

const findAlbumByExactName = `-- name: FindAlbumByExactName :one
SELECT id, name, name_normalized, release_date, description, image_id, pinned, created_at, updated_at FROM albums WHERE name = $1 OR name_normalized = $1 LIMIT 1
`

func (q *Queries) FindAlbumByExactName(ctx context.Context, name string) (Album, error) {
	row := q.db.QueryRow(ctx, findAlbumByExactName, name)
	var i Album
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameNormalized,
		&i.ReleaseDate,
		&i.Description,
		&i.ImageID,
		&i.Pinned,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findAlbumByExactNameForArtists = `-- name: FindAlbumByExactNameForArtists :one
SELECT a.id, a.name, a.name_normalized, a.release_date, a.description, a.image_id, a.pinned, a.created_at, a.updated_at FROM albums a
JOIN album_artists aa ON aa.album_id = a.id
WHERE (a.name = $1::text OR a.name_normalized = $1::text) AND aa.artist_id = ANY($2::bigint[])
LIMIT 1
`

type FindAlbumByExactNameForArtistsParams struct {
	Name      string  `json:"name"`
	ArtistIds []int64 `json:"artist_ids"`
}

func (q *Queries) FindAlbumByExactNameForArtists(ctx context.Context, arg FindAlbumByExactNameForArtistsParams) (Album, error) {
	row := q.db.QueryRow(ctx, findAlbumByExactNameForArtists, arg.Name, arg.ArtistIds)
	var i Album
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameNormalized,
		&i.ReleaseDate,
		&i.Description,
		&i.ImageID,
		&i.Pinned,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findAlbumBySource = `-- name: FindAlbumBySource :one
SELECT a.id, a.name, a.name_normalized, a.release_date, a.description, a.image_id, a.pinned, a.created_at, a.updated_at FROM albums a
JOIN sources s ON s.entity_type = 'album' AND s.entity_id = a.id
WHERE s.source_type = $1 AND s.extracted_id = $2
`

type FindAlbumBySourceParams struct {
	SourceType  SourceType `json:"source_type"`
	ExtractedID *string    `json:"extracted_id"`
}

func (q *Queries) FindAlbumBySource(ctx context.Context, arg FindAlbumBySourceParams) (Album, error) {
	row := q.db.QueryRow(ctx, findAlbumBySource, arg.SourceType, arg.ExtractedID)
	var i Album
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameNormalized,
		&i.ReleaseDate,
		&i.Description,
		&i.ImageID,
		&i.Pinned,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAlbumByID = `-- name: GetAlbumByID :one
SELECT id, name, name_normalized, release_date, description, image_id, pinned, created_at, updated_at FROM albums WHERE id = $1
`

func (q *Queries) GetAlbumByID(ctx context.Context, id int64) (Album, error) {
	row := q.db.QueryRow(ctx, getAlbumByID, id)
	var i Album
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameNormalized,
		&i.ReleaseDate,
		&i.Description,
		&i.ImageID,
		&i.Pinned,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAlbumsByIDs = `-- name: GetAlbumsByIDs :many
SELECT id, name, name_normalized, release_date, description, image_id, pinned, created_at, updated_at FROM albums WHERE id = ANY($1::bigint[])
`

func (q *Queries) GetAlbumsByIDs(ctx context.Context, ids []int64) ([]Album, error) {
	rows, err := q.db.Query(ctx, getAlbumsByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Album
	for rows.Next() {
		var i Album
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NameNormalized,
			&i.ReleaseDate,
			&i.Description,
			&i.ImageID,
			&i.Pinned,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const linkAlbumArtist = `-- name: LinkAlbumArtist :exec
INSERT INTO album_artists (album_id, artist_id, position) VALUES ($1, $2, $3)
ON CONFLICT (album_id, artist_id) DO UPDATE SET position = excluded.position
`

type LinkAlbumArtistParams struct {
	AlbumID  int64 `json:"album_id"`
	ArtistID int64 `json:"artist_id"`
	Position int16 `json:"position"`
}

func (q *Queries) LinkAlbumArtist(ctx context.Context, arg LinkAlbumArtistParams) error {
	_, err := q.db.Exec(ctx, linkAlbumArtist, arg.AlbumID, arg.ArtistID, arg.Position)
	return err
}

const listAlbumArtists = `-- name: ListAlbumArtists :many
SELECT album_id, artist_id, position FROM album_artists WHERE album_id = $1 ORDER BY position
`

func (q *Queries) ListAlbumArtists(ctx context.Context, albumID int64) ([]AlbumArtist, error) {
	rows, err := q.db.Query(ctx, listAlbumArtists, albumID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AlbumArtist
	for rows.Next() {
		var i AlbumArtist
		if err := rows.Scan(&i.AlbumID, &i.ArtistID, &i.Position); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlbums = `-- name: ListAlbums :many
SELECT id, name, name_normalized, release_date, description, image_id, pinned, created_at, updated_at FROM albums WHERE id > $1::bigint ORDER BY id LIMIT $2::int
`

type ListAlbumsParams struct {
	After   int64 `json:"after"`
	MaxRows int32 `json:"max_rows"`
}

func (q *Queries) ListAlbums(ctx context.Context, arg ListAlbumsParams) ([]Album, error) {
	rows, err := q.db.Query(ctx, listAlbums, arg.After, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Album
	for rows.Next() {
		var i Album
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NameNormalized,
			&i.ReleaseDate,
			&i.Description,
			&i.ImageID,
			&i.Pinned,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArtistsForAlbum = `-- name: ListArtistsForAlbum :many
SELECT a.id, a.name, a.name_normalized, a.description, a.image_id, a.pinned, a.created_at, a.updated_at FROM artists a
JOIN album_artists aa ON aa.artist_id = a.id
WHERE aa.album_id = $1
ORDER BY aa.position
`

func (q *Queries) ListArtistsForAlbum(ctx context.Context, albumID int64) ([]Artist, error) {
	rows, err := q.db.Query(ctx, listArtistsForAlbum, albumID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artist
	for rows.Next() {
		var i Artist
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NameNormalized,
			&i.Description,
			&i.ImageID,
			&i.Pinned,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSongsForAlbum = `-- name: ListSongsForAlbum :many
SELECT s.id, s.name, s.name_normalized, s.duration_ms, s.image_id, s.pinned, s.created_at, s.updated_at, sal.track_number FROM songs s
JOIN song_albums sal ON sal.song_id = s.id
WHERE sal.album_id = $1
ORDER BY sal.track_number NULLS LAST, s.name
`

type ListSongsForAlbumRow struct {
	ID             int64              `json:"id"`
	Name           string             `json:"name"`
	NameNormalized string             `json:"name_normalized"`
	DurationMs     *int32             `json:"duration_ms"`
	ImageID        pgtype.UUID        `json:"image_id"`
	Pinned         bool               `json:"pinned"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	TrackNumber    *int32             `json:"track_number"`
}

func (q *Queries) ListSongsForAlbum(ctx context.Context, albumID int64) ([]ListSongsForAlbumRow, error) {
	rows, err := q.db.Query(ctx, listSongsForAlbum, albumID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSongsForAlbumRow
	for rows.Next() {
		var i ListSongsForAlbumRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NameNormalized,
			&i.DurationMs,
			&i.ImageID,
			&i.Pinned,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TrackNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleAlbums = `-- name: ListStaleAlbums :many
SELECT id, name, name_normalized, release_date, description, image_id, pinned, created_at, updated_at FROM albums WHERE updated_at < $1::timestamptz AND NOT pinned ORDER BY updated_at LIMIT $2::int
`

type ListStaleAlbumsParams struct {
	Before  pgtype.Timestamptz `json:"before"`
	MaxRows int32              `json:"max_rows"`
}

func (q *Queries) ListStaleAlbums(ctx context.Context, arg ListStaleAlbumsParams) ([]Album, error) {
	rows, err := q.db.Query(ctx, listStaleAlbums, arg.Before, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Album
	for rows.Next() {
		var i Album
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NameNormalized,
			&i.ReleaseDate,
			&i.Description,
			&i.ImageID,
			&i.Pinned,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAlbumImage = `-- name: SetAlbumImage :one
UPDATE albums SET image_id = $2, pinned = TRUE, updated_at = now() WHERE id = $1 RETURNING id, name, name_normalized, release_date, description, image_id, pinned, created_at, updated_at
`

type SetAlbumImageParams struct {
	ID      int64       `json:"id"`
	ImageID pgtype.UUID `json:"image_id"`
}

func (q *Queries) SetAlbumImage(ctx context.Context, arg SetAlbumImageParams) (Album, error) {
	row := q.db.QueryRow(ctx, setAlbumImage, arg.ID, arg.ImageID)
	var i Album
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameNormalized,
		&i.ReleaseDate,
		&i.Description,
		&i.ImageID,
		&i.Pinned,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setAlbumPinned = `-- name: SetAlbumPinned :one
UPDATE albums SET pinned = $2 WHERE id = $1 RETURNING id, name, name_normalized, release_date, description, image_id, pinned, created_at, updated_at
`

type SetAlbumPinnedParams struct {
	ID     int64 `json:"id"`
	Pinned bool  `json:"pinned"`
}

func (q *Queries) SetAlbumPinned(ctx context.Context, arg SetAlbumPinnedParams) (Album, error) {
	row := q.db.QueryRow(ctx, setAlbumPinned, arg.ID, arg.Pinned)
	var i Album
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameNormalized,
		&i.ReleaseDate,
		&i.Description,
		&i.ImageID,
		&i.Pinned,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAlbum = `-- name: UpdateAlbum :one
UPDATE albums SET name = $2, name_normalized = $3, description = $4, pinned = TRUE, updated_at = now() WHERE id = $1 RETURNING id, name, name_normalized, release_date, description, image_id, pinned, created_at, updated_at
`

type UpdateAlbumParams struct {
	ID             int64   `json:"id"`
	Name           string  `json:"name"`
	NameNormalized string  `json:"name_normalized"`
	Description    *string `json:"description"`
}

func (q *Queries) UpdateAlbum(ctx context.Context, arg UpdateAlbumParams) (Album, error) {
	row := q.db.QueryRow(ctx, updateAlbum,
		arg.ID,
		arg.Name,
		arg.NameNormalized,
		arg.Description,
	)
	var i Album
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameNormalized,
		&i.ReleaseDate,
		&i.Description,
		&i.ImageID,
		&i.Pinned,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAlbumMetadata = `-- name: UpdateAlbumMetadata :exec
UPDATE albums SET description = $2, image_id = $3, updated_at = now() WHERE id = $1 AND NOT pinned
`

type UpdateAlbumMetadataParams struct {
	ID          int64       `json:"id"`
	Description *string     `json:"description"`
	ImageID     pgtype.UUID `json:"image_id"`
}

func (q *Queries) UpdateAlbumMetadata(ctx context.Context, arg UpdateAlbumMetadataParams) error {
	_, err := q.db.Exec(ctx, updateAlbumMetadata, arg.ID, arg.Description, arg.ImageID)
	return err
}
