// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_keys.sql

package db

import (
	"context"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (user_id, name, key_hash) VALUES ($1, $2, $3) RETURNING id, user_id, name, key_hash, last_used_at, created_at
`

type CreateAPIKeyParams struct {
	UserID  int64  `json:"user_id"`
	Name    string `json:"name"`
	KeyHash string `json:"key_hash"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey, arg.UserID, arg.Name, arg.KeyHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.KeyHash,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAPIKey = `-- name: DeleteAPIKey :execrows
DELETE FROM api_keys WHERE id = $1 AND user_id = $2
`

type DeleteAPIKeyParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteAPIKey(ctx context.Context, arg DeleteAPIKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAPIKey, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getUserByAPIKeyHash = `-- name: GetUserByAPIKeyHash :one
SELECT users.id, users.username, users.password_hash, users.display_name, users.description, users.image_id, users.public, users.is_admin, users.created_at FROM users
JOIN api_keys ON api_keys.user_id = users.id
WHERE api_keys.key_hash = $1
`

func (q *Queries) GetUserByAPIKeyHash(ctx context.Context, keyHash string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByAPIKeyHash, keyHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Description,
		&i.ImageID,
		&i.Public,
		&i.IsAdmin,
		&i.CreatedAt,
	)
	return i, err
}

const listAPIKeysForUser = `-- name: ListAPIKeysForUser :many
SELECT id, user_id, name, key_hash, last_used_at, created_at FROM api_keys WHERE user_id = $1 ORDER BY created_at
`

func (q *Queries) ListAPIKeysForUser(ctx context.Context, userID int64) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listAPIKeysForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiKey
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.KeyHash,
			&i.LastUsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchAPIKey = `-- name: TouchAPIKey :exec
UPDATE api_keys SET last_used_at = now() WHERE key_hash = $1
`

func (q *Queries) TouchAPIKey(ctx context.Context, keyHash string) error {
	_, err := q.db.Exec(ctx, touchAPIKey, keyHash)
	return err
}
