// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: artist_blacklist.sql

package db

import (
	"context"
)

const blacklistArtist = `-- name: BlacklistArtist :exec
INSERT INTO artist_blacklist (user_id, artist_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type BlacklistArtistParams struct {
	UserID   int64 `json:"user_id"`
	ArtistID int64 `json:"artist_id"`
}

func (q *Queries) BlacklistArtist(ctx context.Context, arg BlacklistArtistParams) error {
	_, err := q.db.Exec(ctx, blacklistArtist, arg.UserID, arg.ArtistID)
	return err
}

const listBlacklistedArtists = `-- name: ListBlacklistedArtists :many
SELECT a.id, a.name, a.name_normalized, a.name_romanized, a.description, a.image_id, a.pinned, a.created_at, a.updated_at FROM artists a
JOIN artist_blacklist b ON b.artist_id = a.id
WHERE b.user_id = $1
ORDER BY a.name
`

func (q *Queries) ListBlacklistedArtists(ctx context.Context, userID int64) ([]Artist, error) {
	rows, err := q.db.Query(ctx, listBlacklistedArtists, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artist
	for rows.Next() {
		var i Artist
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NameNormalized,
			&i.NameRomanized,
			&i.Description,
			&i.ImageID,
			&i.Pinned,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unblacklistArtist = `-- name: UnblacklistArtist :exec
DELETE FROM artist_blacklist WHERE user_id = $1 AND artist_id = $2
`

type UnblacklistArtistParams struct {
	UserID   int64 `json:"user_id"`
	ArtistID int64 `json:"artist_id"`
}

func (q *Queries) UnblacklistArtist(ctx context.Context, arg UnblacklistArtistParams) error {
	_, err := q.db.Exec(ctx, unblacklistArtist, arg.UserID, arg.ArtistID)
	return err
}
