// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: artists.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createArtist = `-- name: CreateArtist :one
INSERT INTO artists (name, name_normalized) VALUES ($1, $2) RETURNING id, name, name_normalized, description, image_id, pinned, created_at, updated_at
`

type CreateArtistParams struct {
	Name           string `json:"name"`
	NameNormalized string `json:"name_normalized"`
}

func (q *Queries) CreateArtist(ctx context.Context, arg CreateArtistParams) (Artist, error) {
	row := q.db.QueryRow(ctx, createArtist, arg.Name, arg.NameNormalized)
	var i Artist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameNormalized,
		&i.Description,
		&i.ImageID,
		&i.Pinned,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteArtist = `-- name: DeleteArtist :execrows
DELETE FROM artists WHERE id = $1
`

func (q *Queries) DeleteArtist(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteArtist, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findArtistByExactName = `-- name: FindArtistByExactName :one
SELECT id, name, name_normalized, description, image_id, pinned, created_at, updated_at FROM artists WHERE name = $1 OR name_normalized = $1 LIMIT 1
`

func (q *Queries) FindArtistByExactName(ctx context.Context, name string) (Artist, error) {
	row := q.db.QueryRow(ctx, findArtistByExactName, name)
	var i Artist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameNormalized,
		&i.Description,
		&i.ImageID,
		&i.Pinned,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findArtistBySource = `-- name: FindArtistBySource :one
SELECT a.id, a.name, a.name_normalized, a.description, a.image_id, a.pinned, a.created_at, a.updated_at FROM artists a
JOIN sources s ON s.entity_type = 'artist' AND s.entity_id = a.id
WHERE s.source_type = $1 AND s.extracted_id = $2
`

type FindArtistBySourceParams struct {
	SourceType  SourceType `json:"source_type"`
	ExtractedID *string    `json:"extracted_id"`
}

func (q *Queries) FindArtistBySource(ctx context.Context, arg FindArtistBySourceParams) (Artist, error) {
	row := q.db.QueryRow(ctx, findArtistBySource, arg.SourceType, arg.ExtractedID)
	var i Artist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameNormalized,
		&i.Description,
		&i.ImageID,
		&i.Pinned,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getArtistByID = `-- name: GetArtistByID :one
SELECT id, name, name_normalized, description, image_id, pinned, created_at, updated_at FROM artists WHERE id = $1
`

func (q *Queries) GetArtistByID(ctx context.Context, id int64) (Artist, error) {
	row := q.db.QueryRow(ctx, getArtistByID, id)
	var i Artist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameNormalized,
		&i.Description,
		&i.ImageID,
		&i.Pinned,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getArtistsByIDs = `-- name: GetArtistsByIDs :many
SELECT id, name, name_normalized, description, image_id, pinned, created_at, updated_at FROM artists WHERE id = ANY($1::bigint[])
`

func (q *Queries) GetArtistsByIDs(ctx context.Context, ids []int64) ([]Artist, error) {
	rows, err := q.db.Query(ctx, getArtistsByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artist
	for rows.Next() {
		var i Artist
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NameNormalized,
			&i.Description,
			&i.ImageID,
			&i.Pinned,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlbumsForArtist = `-- name: ListAlbumsForArtist :many
SELECT al.id, al.name, al.name_normalized, al.release_date, al.description, al.image_id, al.pinned, al.created_at, al.updated_at FROM albums al
JOIN album_artists aa ON aa.album_id = al.id
WHERE aa.artist_id = $1
ORDER BY al.release_date NULLS LAST, al.name
`

func (q *Queries) ListAlbumsForArtist(ctx context.Context, artistID int64) ([]Album, error) {
	rows, err := q.db.Query(ctx, listAlbumsForArtist, artistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Album
	for rows.Next() {
		var i Album
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NameNormalized,
			&i.ReleaseDate,
			&i.Description,
			&i.ImageID,
			&i.Pinned,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArtists = `-- name: ListArtists :many
SELECT id, name, name_normalized, description, image_id, pinned, created_at, updated_at FROM artists WHERE id > $1::bigint ORDER BY id LIMIT $2::int
`

type ListArtistsParams struct {
	After   int64 `json:"after"`
	MaxRows int32 `json:"max_rows"`
}

func (q *Queries) ListArtists(ctx context.Context, arg ListArtistsParams) ([]Artist, error) {
	rows, err := q.db.Query(ctx, listArtists, arg.After, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artist
	for rows.Next() {
		var i Artist
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NameNormalized,
			&i.Description,
			&i.ImageID,
			&i.Pinned,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSongsForArtist = `-- name: ListSongsForArtist :many
SELECT s.id, s.name, s.name_normalized, s.duration_ms, s.image_id, s.pinned, s.created_at, s.updated_at FROM songs s
JOIN song_artists sa ON sa.song_id = s.id
WHERE sa.artist_id = $1
ORDER BY s.name
`

func (q *Queries) ListSongsForArtist(ctx context.Context, artistID int64) ([]Song, error) {
	rows, err := q.db.Query(ctx, listSongsForArtist, artistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Song
	for rows.Next() {
		var i Song
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NameNormalized,
			&i.DurationMs,
			&i.ImageID,
			&i.Pinned,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleArtists = `-- name: ListStaleArtists :many
SELECT id, name, name_normalized, description, image_id, pinned, created_at, updated_at FROM artists WHERE updated_at < $1::timestamptz AND NOT pinned ORDER BY updated_at LIMIT $2::int
`

type ListStaleArtistsParams struct {
	Before  pgtype.Timestamptz `json:"before"`
	MaxRows int32              `json:"max_rows"`
}

func (q *Queries) ListStaleArtists(ctx context.Context, arg ListStaleArtistsParams) ([]Artist, error) {
	rows, err := q.db.Query(ctx, listStaleArtists, arg.Before, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artist
	for rows.Next() {
		var i Artist
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NameNormalized,
			&i.Description,
			&i.ImageID,
			&i.Pinned,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setArtistImage = `-- name: SetArtistImage :one
UPDATE artists SET image_id = $2, pinned = TRUE, updated_at = now() WHERE id = $1 RETURNING id, name, name_normalized, description, image_id, pinned, created_at, updated_at
`

type SetArtistImageParams struct {
	ID      int64       `json:"id"`
	ImageID pgtype.UUID `json:"image_id"`
}

func (q *Queries) SetArtistImage(ctx context.Context, arg SetArtistImageParams) (Artist, error) {
	row := q.db.QueryRow(ctx, setArtistImage, arg.ID, arg.ImageID)
	var i Artist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameNormalized,
		&i.Description,
		&i.ImageID,
		&i.Pinned,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setArtistPinned = `-- name: SetArtistPinned :one
UPDATE artists SET pinned = $2 WHERE id = $1 RETURNING id, name, name_normalized, description, image_id, pinned, created_at, updated_at
`

type SetArtistPinnedParams struct {
	ID     int64 `json:"id"`
	Pinned bool  `json:"pinned"`
}

func (q *Queries) SetArtistPinned(ctx context.Context, arg SetArtistPinnedParams) (Artist, error) {
	row := q.db.QueryRow(ctx, setArtistPinned, arg.ID, arg.Pinned)
	var i Artist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameNormalized,
		&i.Description,
		&i.ImageID,
		&i.Pinned,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateArtist = `-- name: UpdateArtist :one
UPDATE artists SET name = $2, name_normalized = $3, description = $4, pinned = TRUE, updated_at = now() WHERE id = $1 RETURNING id, name, name_normalized, description, image_id, pinned, created_at, updated_at
`

type UpdateArtistParams struct {
	ID             int64   `json:"id"`
	Name           string  `json:"name"`
	NameNormalized string  `json:"name_normalized"`
	Description    *string `json:"description"`
}

func (q *Queries) UpdateArtist(ctx context.Context, arg UpdateArtistParams) (Artist, error) {
	row := q.db.QueryRow(ctx, updateArtist,
		arg.ID,
		arg.Name,
		arg.NameNormalized,
		arg.Description,
	)
	var i Artist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameNormalized,
		&i.Description,
		&i.ImageID,
		&i.Pinned,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateArtistMetadata = `-- name: UpdateArtistMetadata :exec
UPDATE artists SET description = $2, image_id = $3, updated_at = now() WHERE id = $1 AND NOT pinned
`

type UpdateArtistMetadataParams struct {
	ID          int64       `json:"id"`
	Description *string     `json:"description"`
	ImageID     pgtype.UUID `json:"image_id"`
}

func (q *Queries) UpdateArtistMetadata(ctx context.Context, arg UpdateArtistMetadataParams) error {
	_, err := q.db.Exec(ctx, updateArtistMetadata, arg.ID, arg.Description, arg.ImageID)
	return err
}
