// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: delete_entity.sql

package db

import (
	"context"
)

const deleteAliasesForEntity = `-- name: DeleteAliasesForEntity :exec
DELETE FROM entity_aliases WHERE entity_type = $1::entity_type AND entity_id = $2::bigint
`

type DeleteAliasesForEntityParams struct {
	EntityType EntityType `json:"entity_type"`
	EntityID   int64      `json:"entity_id"`
}

func (q *Queries) DeleteAliasesForEntity(ctx context.Context, arg DeleteAliasesForEntityParams) error {
	_, err := q.db.Exec(ctx, deleteAliasesForEntity, arg.EntityType, arg.EntityID)
	return err
}

const deleteFirstListensForEntity = `-- name: DeleteFirstListensForEntity :exec
DELETE FROM user_entity_first_listen WHERE entity_type = $1::entity_type AND entity_id = $2::bigint
`

type DeleteFirstListensForEntityParams struct {
	EntityType EntityType `json:"entity_type"`
	EntityID   int64      `json:"entity_id"`
}

func (q *Queries) DeleteFirstListensForEntity(ctx context.Context, arg DeleteFirstListensForEntityParams) error {
	_, err := q.db.Exec(ctx, deleteFirstListensForEntity, arg.EntityType, arg.EntityID)
	return err
}

const deleteGlobalStatsForEntity = `-- name: DeleteGlobalStatsForEntity :exec
DELETE FROM entity_global_stats WHERE entity_type = $1::entity_type AND entity_id = $2::bigint
`

type DeleteGlobalStatsForEntityParams struct {
	EntityType EntityType `json:"entity_type"`
	EntityID   int64      `json:"entity_id"`
}

func (q *Queries) DeleteGlobalStatsForEntity(ctx context.Context, arg DeleteGlobalStatsForEntityParams) error {
	_, err := q.db.Exec(ctx, deleteGlobalStatsForEntity, arg.EntityType, arg.EntityID)
	return err
}

const deleteSourcesForEntity = `-- name: DeleteSourcesForEntity :exec
DELETE FROM sources WHERE entity_type = $1::entity_type AND entity_id = $2::bigint
`

type DeleteSourcesForEntityParams struct {
	EntityType EntityType `json:"entity_type"`
	EntityID   int64      `json:"entity_id"`
}

func (q *Queries) DeleteSourcesForEntity(ctx context.Context, arg DeleteSourcesForEntityParams) error {
	_, err := q.db.Exec(ctx, deleteSourcesForEntity, arg.EntityType, arg.EntityID)
	return err
}
