// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: entity_aliases.sql

package db

import (
	"context"
)

const createAlias = `-- name: CreateAlias :one
INSERT INTO entity_aliases (entity_type, entity_id, alias) VALUES ($1, $2, $3)
ON CONFLICT (entity_type, entity_id, alias) DO NOTHING
RETURNING id, entity_type, entity_id, alias, created_at
`

type CreateAliasParams struct {
	EntityType EntityType `json:"entity_type"`
	EntityID   int64      `json:"entity_id"`
	Alias      string     `json:"alias"`
}

func (q *Queries) CreateAlias(ctx context.Context, arg CreateAliasParams) (EntityAlias, error) {
	row := q.db.QueryRow(ctx, createAlias, arg.EntityType, arg.EntityID, arg.Alias)
	var i EntityAlias
	err := row.Scan(
		&i.ID,
		&i.EntityType,
		&i.EntityID,
		&i.Alias,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAlias = `-- name: DeleteAlias :execrows
DELETE FROM entity_aliases WHERE id = $1 AND entity_type = $2 AND entity_id = $3
`

type DeleteAliasParams struct {
	ID         int64      `json:"id"`
	EntityType EntityType `json:"entity_type"`
	EntityID   int64      `json:"entity_id"`
}

func (q *Queries) DeleteAlias(ctx context.Context, arg DeleteAliasParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAlias, arg.ID, arg.EntityType, arg.EntityID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listAliasesForEntity = `-- name: ListAliasesForEntity :many
SELECT id, entity_type, entity_id, alias, created_at FROM entity_aliases WHERE entity_type = $1 AND entity_id = $2 ORDER BY alias
`

type ListAliasesForEntityParams struct {
	EntityType EntityType `json:"entity_type"`
	EntityID   int64      `json:"entity_id"`
}

func (q *Queries) ListAliasesForEntity(ctx context.Context, arg ListAliasesForEntityParams) ([]EntityAlias, error) {
	rows, err := q.db.Query(ctx, listAliasesForEntity, arg.EntityType, arg.EntityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EntityAlias
	for rows.Next() {
		var i EntityAlias
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.EntityID,
			&i.Alias,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const repointAliases = `-- name: RepointAliases :exec
UPDATE entity_aliases SET entity_id = $1::bigint
WHERE entity_type = $2 AND entity_id = $3::bigint
`

type RepointAliasesParams struct {
	NewEntityID int64      `json:"new_entity_id"`
	EntityType  EntityType `json:"entity_type"`
	OldEntityID int64      `json:"old_entity_id"`
}

func (q *Queries) RepointAliases(ctx context.Context, arg RepointAliasesParams) error {
	_, err := q.db.Exec(ctx, repointAliases, arg.NewEntityID, arg.EntityType, arg.OldEntityID)
	return err
}

const searchAliases = `-- name: SearchAliases :many
SELECT id, entity_type, entity_id, alias, created_at FROM entity_aliases WHERE entity_type = $1 AND alias ILIKE '%' || $2::text || '%' LIMIT $3::int
`

type SearchAliasesParams struct {
	EntityType EntityType `json:"entity_type"`
	Query      string     `json:"query"`
	MaxRows    int32      `json:"max_rows"`
}

func (q *Queries) SearchAliases(ctx context.Context, arg SearchAliasesParams) ([]EntityAlias, error) {
	rows, err := q.db.Query(ctx, searchAliases, arg.EntityType, arg.Query, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EntityAlias
	for rows.Next() {
		var i EntityAlias
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.EntityID,
			&i.Alias,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
