// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: import_jobs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelImportJob = `-- name: CancelImportJob :execrows
UPDATE import_jobs SET status = 'cancelled', finished_at = now()
WHERE id = $1 AND user_id = $2 AND status IN ('queued', 'running')
`

type CancelImportJobParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) CancelImportJob(ctx context.Context, arg CancelImportJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, cancelImportJob, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createImportJob = `-- name: CreateImportJob :one
INSERT INTO import_jobs (user_id, batch_id, filename, service, total_items)
VALUES ($1, $2, $3, $4, $5) RETURNING id, user_id, batch_id, filename, service, status, total_items, processed_items, imported_items, skipped_items, failed_items, error_message, created_at, started_at, finished_at
`

type CreateImportJobParams struct {
	UserID     int64         `json:"user_id"`
	BatchID    pgtype.UUID   `json:"batch_id"`
	Filename   string        `json:"filename"`
	Service    ImportService `json:"service"`
	TotalItems int32         `json:"total_items"`
}

func (q *Queries) CreateImportJob(ctx context.Context, arg CreateImportJobParams) (ImportJob, error) {
	row := q.db.QueryRow(ctx, createImportJob,
		arg.UserID,
		arg.BatchID,
		arg.Filename,
		arg.Service,
		arg.TotalItems,
	)
	var i ImportJob
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BatchID,
		&i.Filename,
		&i.Service,
		&i.Status,
		&i.TotalItems,
		&i.ProcessedItems,
		&i.ImportedItems,
		&i.SkippedItems,
		&i.FailedItems,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const finishImportJob = `-- name: FinishImportJob :exec
UPDATE import_jobs SET status = $2, error_message = $3, finished_at = now() WHERE id = $1
`

type FinishImportJobParams struct {
	ID           int64        `json:"id"`
	Status       ImportStatus `json:"status"`
	ErrorMessage *string      `json:"error_message"`
}

func (q *Queries) FinishImportJob(ctx context.Context, arg FinishImportJobParams) error {
	_, err := q.db.Exec(ctx, finishImportJob, arg.ID, arg.Status, arg.ErrorMessage)
	return err
}

const getImportJob = `-- name: GetImportJob :one
SELECT id, user_id, batch_id, filename, service, status, total_items, processed_items, imported_items, skipped_items, failed_items, error_message, created_at, started_at, finished_at FROM import_jobs WHERE id = $1 AND user_id = $2
`

type GetImportJobParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) GetImportJob(ctx context.Context, arg GetImportJobParams) (ImportJob, error) {
	row := q.db.QueryRow(ctx, getImportJob, arg.ID, arg.UserID)
	var i ImportJob
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BatchID,
		&i.Filename,
		&i.Service,
		&i.Status,
		&i.TotalItems,
		&i.ProcessedItems,
		&i.ImportedItems,
		&i.SkippedItems,
		&i.FailedItems,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getImportJobByID = `-- name: GetImportJobByID :one
SELECT id, user_id, batch_id, filename, service, status, total_items, processed_items, imported_items, skipped_items, failed_items, error_message, created_at, started_at, finished_at FROM import_jobs WHERE id = $1
`

func (q *Queries) GetImportJobByID(ctx context.Context, id int64) (ImportJob, error) {
	row := q.db.QueryRow(ctx, getImportJobByID, id)
	var i ImportJob
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BatchID,
		&i.Filename,
		&i.Service,
		&i.Status,
		&i.TotalItems,
		&i.ProcessedItems,
		&i.ImportedItems,
		&i.SkippedItems,
		&i.FailedItems,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const incrementImportProgress = `-- name: IncrementImportProgress :exec
UPDATE import_jobs SET
  processed_items = processed_items + 1,
  imported_items = imported_items + $2::int,
  skipped_items = skipped_items + $3::int,
  failed_items = failed_items + $4::int
WHERE id = $1
`

type IncrementImportProgressParams struct {
	ID       int64 `json:"id"`
	Imported int32 `json:"imported"`
	Skipped  int32 `json:"skipped"`
	Failed   int32 `json:"failed"`
}

func (q *Queries) IncrementImportProgress(ctx context.Context, arg IncrementImportProgressParams) error {
	_, err := q.db.Exec(ctx, incrementImportProgress,
		arg.ID,
		arg.Imported,
		arg.Skipped,
		arg.Failed,
	)
	return err
}

const listImportJobsForUser = `-- name: ListImportJobsForUser :many
SELECT id, user_id, batch_id, filename, service, status, total_items, processed_items, imported_items, skipped_items, failed_items, error_message, created_at, started_at, finished_at FROM import_jobs WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListImportJobsForUser(ctx context.Context, userID int64) ([]ImportJob, error) {
	rows, err := q.db.Query(ctx, listImportJobsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ImportJob
	for rows.Next() {
		var i ImportJob
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.BatchID,
			&i.Filename,
			&i.Service,
			&i.Status,
			&i.TotalItems,
			&i.ProcessedItems,
			&i.ImportedItems,
			&i.SkippedItems,
			&i.FailedItems,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetStaleRunningImportJobs = `-- name: ResetStaleRunningImportJobs :many
UPDATE import_jobs SET status = 'queued', started_at = NULL WHERE status = 'running' RETURNING id, user_id, batch_id, filename, service, status, total_items, processed_items, imported_items, skipped_items, failed_items, error_message, created_at, started_at, finished_at
`

func (q *Queries) ResetStaleRunningImportJobs(ctx context.Context) ([]ImportJob, error) {
	rows, err := q.db.Query(ctx, resetStaleRunningImportJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ImportJob
	for rows.Next() {
		var i ImportJob
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.BatchID,
			&i.Filename,
			&i.Service,
			&i.Status,
			&i.TotalItems,
			&i.ProcessedItems,
			&i.ImportedItems,
			&i.SkippedItems,
			&i.FailedItems,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const startImportJob = `-- name: StartImportJob :exec
UPDATE import_jobs SET status = 'running', started_at = now() WHERE id = $1
`

func (q *Queries) StartImportJob(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, startImportJob, id)
	return err
}
