// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invites.sql

package db

import (
	"context"
)

const claimInvite = `-- name: ClaimInvite :one
UPDATE invites SET uses_count = uses_count + 1
WHERE code = $1 AND (max_uses IS NULL OR uses_count < max_uses)
RETURNING id, code, name, max_uses, uses_count, created_by, created_at
`

func (q *Queries) ClaimInvite(ctx context.Context, code string) (Invite, error) {
	row := q.db.QueryRow(ctx, claimInvite, code)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.MaxUses,
		&i.UsesCount,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createInvite = `-- name: CreateInvite :one
INSERT INTO invites (code, name, max_uses, created_by) VALUES ($1, $2, $3, $4) RETURNING id, code, name, max_uses, uses_count, created_by, created_at
`

type CreateInviteParams struct {
	Code      string `json:"code"`
	Name      string `json:"name"`
	MaxUses   *int32 `json:"max_uses"`
	CreatedBy int64  `json:"created_by"`
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) (Invite, error) {
	row := q.db.QueryRow(ctx, createInvite,
		arg.Code,
		arg.Name,
		arg.MaxUses,
		arg.CreatedBy,
	)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.MaxUses,
		&i.UsesCount,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteInvite = `-- name: DeleteInvite :execrows
DELETE FROM invites WHERE id = $1
`

func (q *Queries) DeleteInvite(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteInvite, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listInvites = `-- name: ListInvites :many
SELECT id, code, name, max_uses, uses_count, created_by, created_at FROM invites ORDER BY created_at DESC
`

func (q *Queries) ListInvites(ctx context.Context) ([]Invite, error) {
	rows, err := q.db.Query(ctx, listInvites)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Invite
	for rows.Next() {
		var i Invite
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.MaxUses,
			&i.UsesCount,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
