// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: listens.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countListensAllFiltered = `-- name: CountListensAllFiltered :one
SELECT count(*) FROM listens l
WHERE l.listened_at >= $1::timestamptz
  AND l.listened_at < $2::timestamptz
  AND ($3::bigint IS NULL OR l.song_id = $3::bigint)
  AND ($4::bigint IS NULL OR EXISTS (
        SELECT 1 FROM song_albums sa WHERE sa.song_id = l.song_id AND sa.album_id = $4::bigint))
  AND ($5::bigint IS NULL OR EXISTS (
        SELECT 1 FROM song_artists sar WHERE sar.song_id = l.song_id AND sar.artist_id = $5::bigint))
  AND ($6::text IS NULL OR EXISTS (
        SELECT 1 FROM sources src WHERE src.entity_type = 'song' AND src.entity_id = l.song_id AND src.source_type = $6::text))
`

type CountListensAllFilteredParams struct {
	FromTime   pgtype.Timestamptz `json:"from_time"`
	ToTime     pgtype.Timestamptz `json:"to_time"`
	SongID     *int64             `json:"song_id"`
	AlbumID    *int64             `json:"album_id"`
	ArtistID   *int64             `json:"artist_id"`
	SourceType *string            `json:"source_type"`
}

func (q *Queries) CountListensAllFiltered(ctx context.Context, arg CountListensAllFilteredParams) (int64, error) {
	row := q.db.QueryRow(ctx, countListensAllFiltered,
		arg.FromTime,
		arg.ToTime,
		arg.SongID,
		arg.AlbumID,
		arg.ArtistID,
		arg.SourceType,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countListensForAlbum = `-- name: CountListensForAlbum :one
SELECT count(*) FROM listens l
JOIN songs s ON s.id = l.song_id
JOIN song_albums sa ON sa.song_id = l.song_id
WHERE sa.album_id = $1::bigint
  AND ($2::bigint IS NULL OR l.user_id = $2::bigint)
  AND (s.duration_ms IS NULL OR s.duration_ms <= 0
       OR coalesce(l.duration_played_ms, s.duration_ms, 0) * 2 >= s.duration_ms
       OR coalesce(l.duration_played_ms, s.duration_ms, 0) >= 240000)
`

type CountListensForAlbumParams struct {
	AlbumID int64  `json:"album_id"`
	UserID  *int64 `json:"user_id"`
}

func (q *Queries) CountListensForAlbum(ctx context.Context, arg CountListensForAlbumParams) (int64, error) {
	row := q.db.QueryRow(ctx, countListensForAlbum, arg.AlbumID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countListensForArtist = `-- name: CountListensForArtist :one
SELECT count(*) FROM listens l
JOIN songs s ON s.id = l.song_id
JOIN song_artists sar ON sar.song_id = l.song_id
WHERE sar.artist_id = $1::bigint
  AND ($2::bigint IS NULL OR l.user_id = $2::bigint)
  AND (s.duration_ms IS NULL OR s.duration_ms <= 0
       OR coalesce(l.duration_played_ms, s.duration_ms, 0) * 2 >= s.duration_ms
       OR coalesce(l.duration_played_ms, s.duration_ms, 0) >= 240000)
`

type CountListensForArtistParams struct {
	ArtistID int64  `json:"artist_id"`
	UserID   *int64 `json:"user_id"`
}

func (q *Queries) CountListensForArtist(ctx context.Context, arg CountListensForArtistParams) (int64, error) {
	row := q.db.QueryRow(ctx, countListensForArtist, arg.ArtistID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countListensForSong = `-- name: CountListensForSong :one
SELECT count(*) FROM listens l
JOIN songs s ON s.id = l.song_id
WHERE l.song_id = $1::bigint
  AND ($2::bigint IS NULL OR l.user_id = $2::bigint)
  AND (s.duration_ms IS NULL OR s.duration_ms <= 0
       OR coalesce(l.duration_played_ms, s.duration_ms, 0) * 2 >= s.duration_ms
       OR coalesce(l.duration_played_ms, s.duration_ms, 0) >= 240000)
`

type CountListensForSongParams struct {
	SongID int64  `json:"song_id"`
	UserID *int64 `json:"user_id"`
}

func (q *Queries) CountListensForSong(ctx context.Context, arg CountListensForSongParams) (int64, error) {
	row := q.db.QueryRow(ctx, countListensForSong, arg.SongID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countListensForUserFiltered = `-- name: CountListensForUserFiltered :one
SELECT count(*) FROM listens l
WHERE l.user_id = $1::bigint
  AND l.listened_at >= $2::timestamptz
  AND l.listened_at < $3::timestamptz
  AND ($4::bigint IS NULL OR l.song_id = $4::bigint)
  AND ($5::bigint IS NULL OR EXISTS (
        SELECT 1 FROM song_albums sa WHERE sa.song_id = l.song_id AND sa.album_id = $5::bigint))
  AND ($6::bigint IS NULL OR EXISTS (
        SELECT 1 FROM song_artists sar WHERE sar.song_id = l.song_id AND sar.artist_id = $6::bigint))
  AND ($7::text IS NULL OR EXISTS (
        SELECT 1 FROM sources src WHERE src.entity_type = 'song' AND src.entity_id = l.song_id AND src.source_type = $7::text))
`

type CountListensForUserFilteredParams struct {
	UserID     int64              `json:"user_id"`
	FromTime   pgtype.Timestamptz `json:"from_time"`
	ToTime     pgtype.Timestamptz `json:"to_time"`
	SongID     *int64             `json:"song_id"`
	AlbumID    *int64             `json:"album_id"`
	ArtistID   *int64             `json:"artist_id"`
	SourceType *string            `json:"source_type"`
}

func (q *Queries) CountListensForUserFiltered(ctx context.Context, arg CountListensForUserFilteredParams) (int64, error) {
	row := q.db.QueryRow(ctx, countListensForUserFiltered,
		arg.UserID,
		arg.FromTime,
		arg.ToTime,
		arg.SongID,
		arg.AlbumID,
		arg.ArtistID,
		arg.SourceType,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createListen = `-- name: CreateListen :one
INSERT INTO listens (user_id, song_id, listened_at, client, duration_played_ms, extra)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (user_id, song_id, listened_at) DO NOTHING
RETURNING id, user_id, song_id, listened_at, client, duration_played_ms, extra, created_at
`

type CreateListenParams struct {
	UserID           int64              `json:"user_id"`
	SongID           int64              `json:"song_id"`
	ListenedAt       pgtype.Timestamptz `json:"listened_at"`
	Client           *string            `json:"client"`
	DurationPlayedMs *int32             `json:"duration_played_ms"`
	Extra            []byte             `json:"extra"`
}

// ON CONFLICT DO NOTHING absorbs a client retry or a re-run bulk import resubmitting the exact
// same listen; the caller sees pgx.ErrNoRows and treats it as an already-recorded no-op.
func (q *Queries) CreateListen(ctx context.Context, arg CreateListenParams) (Listen, error) {
	row := q.db.QueryRow(ctx, createListen,
		arg.UserID,
		arg.SongID,
		arg.ListenedAt,
		arg.Client,
		arg.DurationPlayedMs,
		arg.Extra,
	)
	var i Listen
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SongID,
		&i.ListenedAt,
		&i.Client,
		&i.DurationPlayedMs,
		&i.Extra,
		&i.CreatedAt,
	)
	return i, err
}

const deleteListenForUser = `-- name: DeleteListenForUser :one
DELETE FROM listens WHERE id = $1::bigint AND user_id = $2::bigint
RETURNING id, song_id, listened_at, duration_played_ms
`

type DeleteListenForUserParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

type DeleteListenForUserRow struct {
	ID               int64              `json:"id"`
	SongID           int64              `json:"song_id"`
	ListenedAt       pgtype.Timestamptz `json:"listened_at"`
	DurationPlayedMs *int32             `json:"duration_played_ms"`
}

func (q *Queries) DeleteListenForUser(ctx context.Context, arg DeleteListenForUserParams) (DeleteListenForUserRow, error) {
	row := q.db.QueryRow(ctx, deleteListenForUser, arg.ID, arg.UserID)
	var i DeleteListenForUserRow
	err := row.Scan(
		&i.ID,
		&i.SongID,
		&i.ListenedAt,
		&i.DurationPlayedMs,
	)
	return i, err
}

const earliestListenedAt = `-- name: EarliestListenedAt :one
SELECT min(listened_at)::timestamptz FROM listens
WHERE $1::bigint IS NULL OR user_id = $1::bigint
`

func (q *Queries) EarliestListenedAt(ctx context.Context, userID *int64) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, earliestListenedAt, userID)
	var column_1 pgtype.Timestamptz
	err := row.Scan(&column_1)
	return column_1, err
}

const listListensAllFiltered = `-- name: ListListensAllFiltered :many
SELECT l.id, l.song_id, l.listened_at, l.duration_played_ms, u.id AS user_id, u.public, u.username, u.display_name, u.image_id AS user_image_id
FROM listens l
JOIN users u ON u.id = l.user_id
WHERE l.listened_at >= $1::timestamptz
  AND l.listened_at < $2::timestamptz
  AND ($3::bigint IS NULL OR l.song_id = $3::bigint)
  AND ($4::bigint IS NULL OR EXISTS (
        SELECT 1 FROM song_albums sa WHERE sa.song_id = l.song_id AND sa.album_id = $4::bigint))
  AND ($5::bigint IS NULL OR EXISTS (
        SELECT 1 FROM song_artists sar WHERE sar.song_id = l.song_id AND sar.artist_id = $5::bigint))
  AND ($6::text IS NULL OR EXISTS (
        SELECT 1 FROM sources src WHERE src.entity_type = 'song' AND src.entity_id = l.song_id AND src.source_type = $6::text))
ORDER BY l.listened_at DESC
LIMIT $8::int OFFSET $7::int
`

type ListListensAllFilteredParams struct {
	FromTime   pgtype.Timestamptz `json:"from_time"`
	ToTime     pgtype.Timestamptz `json:"to_time"`
	SongID     *int64             `json:"song_id"`
	AlbumID    *int64             `json:"album_id"`
	ArtistID   *int64             `json:"artist_id"`
	SourceType *string            `json:"source_type"`
	RowOffset  int32              `json:"row_offset"`
	MaxRows    int32              `json:"max_rows"`
}

type ListListensAllFilteredRow struct {
	ID               int64              `json:"id"`
	SongID           int64              `json:"song_id"`
	ListenedAt       pgtype.Timestamptz `json:"listened_at"`
	DurationPlayedMs *int32             `json:"duration_played_ms"`
	UserID           int64              `json:"user_id"`
	Public           bool               `json:"public"`
	Username         string             `json:"username"`
	DisplayName      *string            `json:"display_name"`
	UserImageID      pgtype.UUID        `json:"user_image_id"`
}

func (q *Queries) ListListensAllFiltered(ctx context.Context, arg ListListensAllFilteredParams) ([]ListListensAllFilteredRow, error) {
	rows, err := q.db.Query(ctx, listListensAllFiltered,
		arg.FromTime,
		arg.ToTime,
		arg.SongID,
		arg.AlbumID,
		arg.ArtistID,
		arg.SourceType,
		arg.RowOffset,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListListensAllFilteredRow
	for rows.Next() {
		var i ListListensAllFilteredRow
		if err := rows.Scan(
			&i.ID,
			&i.SongID,
			&i.ListenedAt,
			&i.DurationPlayedMs,
			&i.UserID,
			&i.Public,
			&i.Username,
			&i.DisplayName,
			&i.UserImageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listListensForAlbum = `-- name: ListListensForAlbum :many
SELECT l.id, l.song_id, l.listened_at, u.id AS user_id, u.public, u.username, u.display_name, u.image_id AS user_image_id
FROM listens l
JOIN songs s ON s.id = l.song_id
JOIN song_albums sa ON sa.song_id = l.song_id
JOIN users u ON u.id = l.user_id
WHERE sa.album_id = $1::bigint
  AND ($2::bigint IS NULL OR l.user_id = $2::bigint)
  AND (s.duration_ms IS NULL OR s.duration_ms <= 0
       OR coalesce(l.duration_played_ms, s.duration_ms, 0) * 2 >= s.duration_ms
       OR coalesce(l.duration_played_ms, s.duration_ms, 0) >= 240000)
ORDER BY l.listened_at DESC
LIMIT $4::int OFFSET $3::int
`

type ListListensForAlbumParams struct {
	AlbumID   int64  `json:"album_id"`
	UserID    *int64 `json:"user_id"`
	RowOffset int32  `json:"row_offset"`
	MaxRows   int32  `json:"max_rows"`
}

type ListListensForAlbumRow struct {
	ID          int64              `json:"id"`
	SongID      int64              `json:"song_id"`
	ListenedAt  pgtype.Timestamptz `json:"listened_at"`
	UserID      int64              `json:"user_id"`
	Public      bool               `json:"public"`
	Username    string             `json:"username"`
	DisplayName *string            `json:"display_name"`
	UserImageID pgtype.UUID        `json:"user_image_id"`
}

// Eligibility-filtered; see ListListensForSong.
func (q *Queries) ListListensForAlbum(ctx context.Context, arg ListListensForAlbumParams) ([]ListListensForAlbumRow, error) {
	rows, err := q.db.Query(ctx, listListensForAlbum,
		arg.AlbumID,
		arg.UserID,
		arg.RowOffset,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListListensForAlbumRow
	for rows.Next() {
		var i ListListensForAlbumRow
		if err := rows.Scan(
			&i.ID,
			&i.SongID,
			&i.ListenedAt,
			&i.UserID,
			&i.Public,
			&i.Username,
			&i.DisplayName,
			&i.UserImageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listListensForArtist = `-- name: ListListensForArtist :many
SELECT l.id, l.song_id, l.listened_at, u.id AS user_id, u.public, u.username, u.display_name, u.image_id AS user_image_id
FROM listens l
JOIN songs s ON s.id = l.song_id
JOIN song_artists sar ON sar.song_id = l.song_id
JOIN users u ON u.id = l.user_id
WHERE sar.artist_id = $1::bigint
  AND ($2::bigint IS NULL OR l.user_id = $2::bigint)
  AND (s.duration_ms IS NULL OR s.duration_ms <= 0
       OR coalesce(l.duration_played_ms, s.duration_ms, 0) * 2 >= s.duration_ms
       OR coalesce(l.duration_played_ms, s.duration_ms, 0) >= 240000)
ORDER BY l.listened_at DESC
LIMIT $4::int OFFSET $3::int
`

type ListListensForArtistParams struct {
	ArtistID  int64  `json:"artist_id"`
	UserID    *int64 `json:"user_id"`
	RowOffset int32  `json:"row_offset"`
	MaxRows   int32  `json:"max_rows"`
}

type ListListensForArtistRow struct {
	ID          int64              `json:"id"`
	SongID      int64              `json:"song_id"`
	ListenedAt  pgtype.Timestamptz `json:"listened_at"`
	UserID      int64              `json:"user_id"`
	Public      bool               `json:"public"`
	Username    string             `json:"username"`
	DisplayName *string            `json:"display_name"`
	UserImageID pgtype.UUID        `json:"user_image_id"`
}

// Eligibility-filtered; see ListListensForSong.
func (q *Queries) ListListensForArtist(ctx context.Context, arg ListListensForArtistParams) ([]ListListensForArtistRow, error) {
	rows, err := q.db.Query(ctx, listListensForArtist,
		arg.ArtistID,
		arg.UserID,
		arg.RowOffset,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListListensForArtistRow
	for rows.Next() {
		var i ListListensForArtistRow
		if err := rows.Scan(
			&i.ID,
			&i.SongID,
			&i.ListenedAt,
			&i.UserID,
			&i.Public,
			&i.Username,
			&i.DisplayName,
			&i.UserImageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listListensForSong = `-- name: ListListensForSong :many
SELECT l.id, l.song_id, l.listened_at, u.id AS user_id, u.public, u.username, u.display_name, u.image_id AS user_image_id
FROM listens l
JOIN songs s ON s.id = l.song_id
JOIN users u ON u.id = l.user_id
WHERE l.song_id = $1::bigint
  AND ($2::bigint IS NULL OR l.user_id = $2::bigint)
  AND (s.duration_ms IS NULL OR s.duration_ms <= 0
       OR coalesce(l.duration_played_ms, s.duration_ms, 0) * 2 >= s.duration_ms
       OR coalesce(l.duration_played_ms, s.duration_ms, 0) >= 240000)
ORDER BY l.listened_at DESC
LIMIT $4::int OFFSET $3::int
`

type ListListensForSongParams struct {
	SongID    int64  `json:"song_id"`
	UserID    *int64 `json:"user_id"`
	RowOffset int32  `json:"row_offset"`
	MaxRows   int32  `json:"max_rows"`
}

type ListListensForSongRow struct {
	ID          int64              `json:"id"`
	SongID      int64              `json:"song_id"`
	ListenedAt  pgtype.Timestamptz `json:"listened_at"`
	UserID      int64              `json:"user_id"`
	Public      bool               `json:"public"`
	Username    string             `json:"username"`
	DisplayName *string            `json:"display_name"`
	UserImageID pgtype.UUID        `json:"user_image_id"`
}

// Eligibility-filtered (rollup.Eligible's threshold) so this list, its count, and the song's
// entity_global_stats.plays all agree on what counts as a real listen. user_id optionally
// scopes to one caller-permitted user (already checked upstream).
func (q *Queries) ListListensForSong(ctx context.Context, arg ListListensForSongParams) ([]ListListensForSongRow, error) {
	rows, err := q.db.Query(ctx, listListensForSong,
		arg.SongID,
		arg.UserID,
		arg.RowOffset,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListListensForSongRow
	for rows.Next() {
		var i ListListensForSongRow
		if err := rows.Scan(
			&i.ID,
			&i.SongID,
			&i.ListenedAt,
			&i.UserID,
			&i.Public,
			&i.Username,
			&i.DisplayName,
			&i.UserImageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listListensForUser = `-- name: ListListensForUser :many
SELECT id, user_id, song_id, listened_at, client, duration_played_ms, extra, created_at FROM listens WHERE user_id = $1::bigint
ORDER BY listened_at
LIMIT $3::int OFFSET $2::int
`

type ListListensForUserParams struct {
	UserID    int64 `json:"user_id"`
	RowOffset int32 `json:"row_offset"`
	MaxRows   int32 `json:"max_rows"`
}

func (q *Queries) ListListensForUser(ctx context.Context, arg ListListensForUserParams) ([]Listen, error) {
	rows, err := q.db.Query(ctx, listListensForUser, arg.UserID, arg.RowOffset, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Listen
	for rows.Next() {
		var i Listen
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SongID,
			&i.ListenedAt,
			&i.Client,
			&i.DurationPlayedMs,
			&i.Extra,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listListensForUserFiltered = `-- name: ListListensForUserFiltered :many
SELECT l.id, l.user_id, l.song_id, l.listened_at, l.client, l.duration_played_ms, l.extra, l.created_at FROM listens l
WHERE l.user_id = $1::bigint
  AND l.listened_at >= $2::timestamptz
  AND l.listened_at < $3::timestamptz
  AND ($4::bigint IS NULL OR l.song_id = $4::bigint)
  AND ($5::bigint IS NULL OR EXISTS (
        SELECT 1 FROM song_albums sa WHERE sa.song_id = l.song_id AND sa.album_id = $5::bigint))
  AND ($6::bigint IS NULL OR EXISTS (
        SELECT 1 FROM song_artists sar WHERE sar.song_id = l.song_id AND sar.artist_id = $6::bigint))
  AND ($7::text IS NULL OR EXISTS (
        SELECT 1 FROM sources src WHERE src.entity_type = 'song' AND src.entity_id = l.song_id AND src.source_type = $7::text))
ORDER BY l.listened_at DESC
LIMIT $9::int OFFSET $8::int
`

type ListListensForUserFilteredParams struct {
	UserID     int64              `json:"user_id"`
	FromTime   pgtype.Timestamptz `json:"from_time"`
	ToTime     pgtype.Timestamptz `json:"to_time"`
	SongID     *int64             `json:"song_id"`
	AlbumID    *int64             `json:"album_id"`
	ArtistID   *int64             `json:"artist_id"`
	SourceType *string            `json:"source_type"`
	RowOffset  int32              `json:"row_offset"`
	MaxRows    int32              `json:"max_rows"`
}

func (q *Queries) ListListensForUserFiltered(ctx context.Context, arg ListListensForUserFilteredParams) ([]Listen, error) {
	rows, err := q.db.Query(ctx, listListensForUserFiltered,
		arg.UserID,
		arg.FromTime,
		arg.ToTime,
		arg.SongID,
		arg.AlbumID,
		arg.ArtistID,
		arg.SourceType,
		arg.RowOffset,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Listen
	for rows.Next() {
		var i Listen
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SongID,
			&i.ListenedAt,
			&i.Client,
			&i.DurationPlayedMs,
			&i.Extra,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchListensForUser = `-- name: SearchListensForUser :many
SELECT l.id, l.song_id, l.listened_at
FROM listens l
JOIN songs s ON s.id = l.song_id
WHERE l.user_id = $1::bigint
  AND (
    s.name ILIKE '%' || $2::text || '%'
    OR EXISTS (
      SELECT 1 FROM song_artists sa JOIN artists a ON a.id = sa.artist_id
      WHERE sa.song_id = s.id AND a.name ILIKE '%' || $2::text || '%'
    )
  )
ORDER BY l.listened_at DESC
LIMIT $3::int
`

type SearchListensForUserParams struct {
	UserID  int64  `json:"user_id"`
	Query   string `json:"query"`
	MaxRows int32  `json:"max_rows"`
}

type SearchListensForUserRow struct {
	ID         int64              `json:"id"`
	SongID     int64              `json:"song_id"`
	ListenedAt pgtype.Timestamptz `json:"listened_at"`
}

func (q *Queries) SearchListensForUser(ctx context.Context, arg SearchListensForUserParams) ([]SearchListensForUserRow, error) {
	rows, err := q.db.Query(ctx, searchListensForUser, arg.UserID, arg.Query, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchListensForUserRow
	for rows.Next() {
		var i SearchListensForUserRow
		if err := rows.Scan(&i.ID, &i.SongID, &i.ListenedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
