// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: listens.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createListen = `-- name: CreateListen :one
INSERT INTO listens (user_id, song_id, listened_at, client, duration_played_ms, extra)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, song_id, listened_at, client, duration_played_ms, extra, created_at
`

type CreateListenParams struct {
	UserID           int64              `json:"user_id"`
	SongID           int64              `json:"song_id"`
	ListenedAt       pgtype.Timestamptz `json:"listened_at"`
	Client           *string            `json:"client"`
	DurationPlayedMs *int32             `json:"duration_played_ms"`
	Extra            []byte             `json:"extra"`
}

func (q *Queries) CreateListen(ctx context.Context, arg CreateListenParams) (Listen, error) {
	row := q.db.QueryRow(ctx, createListen,
		arg.UserID,
		arg.SongID,
		arg.ListenedAt,
		arg.Client,
		arg.DurationPlayedMs,
		arg.Extra,
	)
	var i Listen
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SongID,
		&i.ListenedAt,
		&i.Client,
		&i.DurationPlayedMs,
		&i.Extra,
		&i.CreatedAt,
	)
	return i, err
}

const listListensForUser = `-- name: ListListensForUser :many
SELECT id, user_id, song_id, listened_at, client, duration_played_ms, extra, created_at FROM listens WHERE user_id = $1::bigint
ORDER BY listened_at
LIMIT $3::int OFFSET $2::int
`

type ListListensForUserParams struct {
	UserID    int64 `json:"user_id"`
	RowOffset int32 `json:"row_offset"`
	MaxRows   int32 `json:"max_rows"`
}

func (q *Queries) ListListensForUser(ctx context.Context, arg ListListensForUserParams) ([]Listen, error) {
	rows, err := q.db.Query(ctx, listListensForUser, arg.UserID, arg.RowOffset, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Listen
	for rows.Next() {
		var i Listen
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SongID,
			&i.ListenedAt,
			&i.Client,
			&i.DurationPlayedMs,
			&i.Extra,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchListensForUser = `-- name: SearchListensForUser :many
SELECT l.id, l.song_id, l.listened_at
FROM listens l
JOIN songs s ON s.id = l.song_id
WHERE l.user_id = $1::bigint
  AND (
    s.name ILIKE '%' || $2::text || '%'
    OR EXISTS (
      SELECT 1 FROM song_artists sa JOIN artists a ON a.id = sa.artist_id
      WHERE sa.song_id = s.id AND a.name ILIKE '%' || $2::text || '%'
    )
  )
ORDER BY l.listened_at DESC
LIMIT $3::int
`

type SearchListensForUserParams struct {
	UserID  int64  `json:"user_id"`
	Query   string `json:"query"`
	MaxRows int32  `json:"max_rows"`
}

type SearchListensForUserRow struct {
	ID         int64              `json:"id"`
	SongID     int64              `json:"song_id"`
	ListenedAt pgtype.Timestamptz `json:"listened_at"`
}

func (q *Queries) SearchListensForUser(ctx context.Context, arg SearchListensForUserParams) ([]SearchListensForUserRow, error) {
	rows, err := q.db.Query(ctx, searchListensForUser, arg.UserID, arg.Query, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchListensForUserRow
	for rows.Next() {
		var i SearchListensForUserRow
		if err := rows.Scan(&i.ID, &i.SongID, &i.ListenedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
