// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: locks.sql

package db

import (
	"context"
)

const advisoryLockKey = `-- name: AdvisoryLockKey :exec
SELECT pg_advisory_xact_lock(hashtextextended($1::text, $2::bigint))
`

type AdvisoryLockKeyParams struct {
	Key  string `json:"key"`
	Seed int64  `json:"seed"`
}

func (q *Queries) AdvisoryLockKey(ctx context.Context, arg AdvisoryLockKeyParams) error {
	_, err := q.db.Exec(ctx, advisoryLockKey, arg.Key, arg.Seed)
	return err
}
