// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: locks.sql

package db

import (
	"context"
)

const advisoryLockEntityName = `-- name: AdvisoryLockEntityName :exec
SELECT pg_advisory_xact_lock(hashtextextended($1::text, $2::bigint))
`

type AdvisoryLockEntityNameParams struct {
	NameNormalized string `json:"name_normalized"`
	Seed           int64  `json:"seed"`
}

func (q *Queries) AdvisoryLockEntityName(ctx context.Context, arg AdvisoryLockEntityNameParams) error {
	_, err := q.db.Exec(ctx, advisoryLockEntityName, arg.NameNormalized, arg.Seed)
	return err
}
