// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: merge.sql

package db

import (
	"context"
)

const deleteRemainingAlbumArtistsForAlbum = `-- name: DeleteRemainingAlbumArtistsForAlbum :exec
DELETE FROM album_artists WHERE album_id = $1::bigint
`

func (q *Queries) DeleteRemainingAlbumArtistsForAlbum(ctx context.Context, oldAlbumID int64) error {
	_, err := q.db.Exec(ctx, deleteRemainingAlbumArtistsForAlbum, oldAlbumID)
	return err
}

const deleteRemainingAlbumArtistsForArtist = `-- name: DeleteRemainingAlbumArtistsForArtist :exec
DELETE FROM album_artists WHERE artist_id = $1::bigint
`

func (q *Queries) DeleteRemainingAlbumArtistsForArtist(ctx context.Context, oldArtistID int64) error {
	_, err := q.db.Exec(ctx, deleteRemainingAlbumArtistsForArtist, oldArtistID)
	return err
}

const deleteRemainingBlacklistForArtist = `-- name: DeleteRemainingBlacklistForArtist :exec
DELETE FROM artist_blacklist WHERE artist_id = $1::bigint
`

func (q *Queries) DeleteRemainingBlacklistForArtist(ctx context.Context, oldArtistID int64) error {
	_, err := q.db.Exec(ctx, deleteRemainingBlacklistForArtist, oldArtistID)
	return err
}

const deleteRemainingSongAlbumsForAlbum = `-- name: DeleteRemainingSongAlbumsForAlbum :exec
DELETE FROM song_albums WHERE album_id = $1::bigint
`

func (q *Queries) DeleteRemainingSongAlbumsForAlbum(ctx context.Context, oldAlbumID int64) error {
	_, err := q.db.Exec(ctx, deleteRemainingSongAlbumsForAlbum, oldAlbumID)
	return err
}

const deleteRemainingSongAlbumsForSong = `-- name: DeleteRemainingSongAlbumsForSong :exec
DELETE FROM song_albums WHERE song_id = $1::bigint
`

func (q *Queries) DeleteRemainingSongAlbumsForSong(ctx context.Context, oldSongID int64) error {
	_, err := q.db.Exec(ctx, deleteRemainingSongAlbumsForSong, oldSongID)
	return err
}

const deleteRemainingSongArtistsForArtist = `-- name: DeleteRemainingSongArtistsForArtist :exec
DELETE FROM song_artists WHERE artist_id = $1::bigint
`

func (q *Queries) DeleteRemainingSongArtistsForArtist(ctx context.Context, oldArtistID int64) error {
	_, err := q.db.Exec(ctx, deleteRemainingSongArtistsForArtist, oldArtistID)
	return err
}

const deleteRemainingSongArtistsForSong = `-- name: DeleteRemainingSongArtistsForSong :exec
DELETE FROM song_artists WHERE song_id = $1::bigint
`

func (q *Queries) DeleteRemainingSongArtistsForSong(ctx context.Context, oldSongID int64) error {
	_, err := q.db.Exec(ctx, deleteRemainingSongArtistsForSong, oldSongID)
	return err
}

const repointAlbumArtistsForAlbumMerge = `-- name: RepointAlbumArtistsForAlbumMerge :exec
UPDATE album_artists SET album_id = $1::bigint
WHERE album_id = $2::bigint
  AND artist_id NOT IN (SELECT artist_id FROM album_artists WHERE album_id = $1::bigint)
`

type RepointAlbumArtistsForAlbumMergeParams struct {
	NewAlbumID int64 `json:"new_album_id"`
	OldAlbumID int64 `json:"old_album_id"`
}

func (q *Queries) RepointAlbumArtistsForAlbumMerge(ctx context.Context, arg RepointAlbumArtistsForAlbumMergeParams) error {
	_, err := q.db.Exec(ctx, repointAlbumArtistsForAlbumMerge, arg.NewAlbumID, arg.OldAlbumID)
	return err
}

const repointAlbumArtistsForArtistMerge = `-- name: RepointAlbumArtistsForArtistMerge :exec
UPDATE album_artists SET artist_id = $1::bigint
WHERE artist_id = $2::bigint
  AND album_id NOT IN (SELECT album_id FROM album_artists WHERE artist_id = $1::bigint)
`

type RepointAlbumArtistsForArtistMergeParams struct {
	NewArtistID int64 `json:"new_artist_id"`
	OldArtistID int64 `json:"old_artist_id"`
}

func (q *Queries) RepointAlbumArtistsForArtistMerge(ctx context.Context, arg RepointAlbumArtistsForArtistMergeParams) error {
	_, err := q.db.Exec(ctx, repointAlbumArtistsForArtistMerge, arg.NewArtistID, arg.OldArtistID)
	return err
}

const repointBlacklistForArtistMerge = `-- name: RepointBlacklistForArtistMerge :exec
UPDATE artist_blacklist SET artist_id = $1::bigint
WHERE artist_id = $2::bigint
  AND user_id NOT IN (SELECT user_id FROM artist_blacklist WHERE artist_id = $1::bigint)
`

type RepointBlacklistForArtistMergeParams struct {
	NewArtistID int64 `json:"new_artist_id"`
	OldArtistID int64 `json:"old_artist_id"`
}

func (q *Queries) RepointBlacklistForArtistMerge(ctx context.Context, arg RepointBlacklistForArtistMergeParams) error {
	_, err := q.db.Exec(ctx, repointBlacklistForArtistMerge, arg.NewArtistID, arg.OldArtistID)
	return err
}

const repointListensForSongMerge = `-- name: RepointListensForSongMerge :exec
UPDATE listens SET song_id = $1::bigint WHERE song_id = $2::bigint
`

type RepointListensForSongMergeParams struct {
	NewSongID int64 `json:"new_song_id"`
	OldSongID int64 `json:"old_song_id"`
}

func (q *Queries) RepointListensForSongMerge(ctx context.Context, arg RepointListensForSongMergeParams) error {
	_, err := q.db.Exec(ctx, repointListensForSongMerge, arg.NewSongID, arg.OldSongID)
	return err
}

const repointNowPlayingForSongMerge = `-- name: RepointNowPlayingForSongMerge :exec
UPDATE now_playing SET song_id = $1::bigint WHERE song_id = $2::bigint
`

type RepointNowPlayingForSongMergeParams struct {
	NewSongID int64 `json:"new_song_id"`
	OldSongID int64 `json:"old_song_id"`
}

func (q *Queries) RepointNowPlayingForSongMerge(ctx context.Context, arg RepointNowPlayingForSongMergeParams) error {
	_, err := q.db.Exec(ctx, repointNowPlayingForSongMerge, arg.NewSongID, arg.OldSongID)
	return err
}

const repointSongAlbumsForAlbumMerge = `-- name: RepointSongAlbumsForAlbumMerge :exec
UPDATE song_albums SET album_id = $1::bigint
WHERE album_id = $2::bigint
  AND song_id NOT IN (SELECT song_id FROM song_albums WHERE album_id = $1::bigint)
`

type RepointSongAlbumsForAlbumMergeParams struct {
	NewAlbumID int64 `json:"new_album_id"`
	OldAlbumID int64 `json:"old_album_id"`
}

func (q *Queries) RepointSongAlbumsForAlbumMerge(ctx context.Context, arg RepointSongAlbumsForAlbumMergeParams) error {
	_, err := q.db.Exec(ctx, repointSongAlbumsForAlbumMerge, arg.NewAlbumID, arg.OldAlbumID)
	return err
}

const repointSongAlbumsForSongMerge = `-- name: RepointSongAlbumsForSongMerge :exec
UPDATE song_albums SET song_id = $1::bigint
WHERE song_id = $2::bigint
  AND album_id NOT IN (SELECT album_id FROM song_albums WHERE song_id = $1::bigint)
`

type RepointSongAlbumsForSongMergeParams struct {
	NewSongID int64 `json:"new_song_id"`
	OldSongID int64 `json:"old_song_id"`
}

func (q *Queries) RepointSongAlbumsForSongMerge(ctx context.Context, arg RepointSongAlbumsForSongMergeParams) error {
	_, err := q.db.Exec(ctx, repointSongAlbumsForSongMerge, arg.NewSongID, arg.OldSongID)
	return err
}

const repointSongArtistsForArtistMerge = `-- name: RepointSongArtistsForArtistMerge :exec
UPDATE song_artists SET artist_id = $1::bigint
WHERE artist_id = $2::bigint
  AND song_id NOT IN (SELECT song_id FROM song_artists WHERE artist_id = $1::bigint)
`

type RepointSongArtistsForArtistMergeParams struct {
	NewArtistID int64 `json:"new_artist_id"`
	OldArtistID int64 `json:"old_artist_id"`
}

func (q *Queries) RepointSongArtistsForArtistMerge(ctx context.Context, arg RepointSongArtistsForArtistMergeParams) error {
	_, err := q.db.Exec(ctx, repointSongArtistsForArtistMerge, arg.NewArtistID, arg.OldArtistID)
	return err
}

const repointSongArtistsForSongMerge = `-- name: RepointSongArtistsForSongMerge :exec
UPDATE song_artists SET song_id = $1::bigint
WHERE song_id = $2::bigint
  AND artist_id NOT IN (SELECT artist_id FROM song_artists WHERE song_id = $1::bigint)
`

type RepointSongArtistsForSongMergeParams struct {
	NewSongID int64 `json:"new_song_id"`
	OldSongID int64 `json:"old_song_id"`
}

func (q *Queries) RepointSongArtistsForSongMerge(ctx context.Context, arg RepointSongArtistsForSongMergeParams) error {
	_, err := q.db.Exec(ctx, repointSongArtistsForSongMerge, arg.NewSongID, arg.OldSongID)
	return err
}

const repointSourcesForMerge = `-- name: RepointSourcesForMerge :exec
UPDATE sources SET entity_id = $1::bigint
WHERE entity_type = $2 AND entity_id = $3::bigint
`

type RepointSourcesForMergeParams struct {
	NewEntityID int64      `json:"new_entity_id"`
	EntityType  EntityType `json:"entity_type"`
	OldEntityID int64      `json:"old_entity_id"`
}

func (q *Queries) RepointSourcesForMerge(ctx context.Context, arg RepointSourcesForMergeParams) error {
	_, err := q.db.Exec(ctx, repointSourcesForMerge, arg.NewEntityID, arg.EntityType, arg.OldEntityID)
	return err
}
