// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: merge_suggestions.sql

package db

import (
	"context"
)

const deleteMergeSuggestionsForEntity = `-- name: DeleteMergeSuggestionsForEntity :exec
DELETE FROM merge_suggestions WHERE entity_type = $1::entity_type AND (lo_id = $2::bigint OR hi_id = $2::bigint)
`

type DeleteMergeSuggestionsForEntityParams struct {
	EntityType EntityType `json:"entity_type"`
	EntityID   int64      `json:"entity_id"`
}

func (q *Queries) DeleteMergeSuggestionsForEntity(ctx context.Context, arg DeleteMergeSuggestionsForEntityParams) error {
	_, err := q.db.Exec(ctx, deleteMergeSuggestionsForEntity, arg.EntityType, arg.EntityID)
	return err
}

const listMergeSuggestions = `-- name: ListMergeSuggestions :many
SELECT id, entity_type, lo_id, hi_id, score, rejected, created_at FROM merge_suggestions WHERE entity_type = $1 AND NOT rejected ORDER BY score DESC
`

func (q *Queries) ListMergeSuggestions(ctx context.Context, entityType EntityType) ([]MergeSuggestion, error) {
	rows, err := q.db.Query(ctx, listMergeSuggestions, entityType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MergeSuggestion
	for rows.Next() {
		var i MergeSuggestion
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.LoID,
			&i.HiID,
			&i.Score,
			&i.Rejected,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queueMergeSuggestion = `-- name: QueueMergeSuggestion :exec
INSERT INTO merge_suggestions (entity_type, lo_id, hi_id, score)
VALUES ($1::entity_type, LEAST($2::bigint, $3::bigint), GREATEST($2::bigint, $3::bigint), $4::real)
ON CONFLICT (entity_type, lo_id, hi_id) DO NOTHING
`

type QueueMergeSuggestionParams struct {
	EntityType EntityType `json:"entity_type"`
	A          int64      `json:"a"`
	B          int64      `json:"b"`
	Score      float32    `json:"score"`
}

func (q *Queries) QueueMergeSuggestion(ctx context.Context, arg QueueMergeSuggestionParams) error {
	_, err := q.db.Exec(ctx, queueMergeSuggestion,
		arg.EntityType,
		arg.A,
		arg.B,
		arg.Score,
	)
	return err
}

const rejectMergeSuggestion = `-- name: RejectMergeSuggestion :exec
UPDATE merge_suggestions SET rejected = TRUE WHERE id = $1
`

func (q *Queries) RejectMergeSuggestion(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, rejectMergeSuggestion, id)
	return err
}
