// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type CorrelationMethod string

const (
	CorrelationMethodSourceID  CorrelationMethod = "source_id"
	CorrelationMethodFuzzyName CorrelationMethod = "fuzzy_name"
	CorrelationMethodManual    CorrelationMethod = "manual"
)

func (e *CorrelationMethod) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CorrelationMethod(s)
	case string:
		*e = CorrelationMethod(s)
	default:
		return fmt.Errorf("unsupported scan type for CorrelationMethod: %T", src)
	}
	return nil
}

type NullCorrelationMethod struct {
	CorrelationMethod CorrelationMethod `json:"correlation_method"`
	Valid             bool              `json:"valid"` // Valid is true if CorrelationMethod is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCorrelationMethod) Scan(value interface{}) error {
	if value == nil {
		ns.CorrelationMethod, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CorrelationMethod.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCorrelationMethod) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CorrelationMethod), nil
}

type EntityType string

const (
	EntityTypeArtist EntityType = "artist"
	EntityTypeAlbum  EntityType = "album"
	EntityTypeSong   EntityType = "song"
)

func (e *EntityType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EntityType(s)
	case string:
		*e = EntityType(s)
	default:
		return fmt.Errorf("unsupported scan type for EntityType: %T", src)
	}
	return nil
}

type NullEntityType struct {
	EntityType EntityType `json:"entity_type"`
	Valid      bool       `json:"valid"` // Valid is true if EntityType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEntityType) Scan(value interface{}) error {
	if value == nil {
		ns.EntityType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EntityType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEntityType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EntityType), nil
}

type ImportStatus string

const (
	ImportStatusQueued    ImportStatus = "queued"
	ImportStatusRunning   ImportStatus = "running"
	ImportStatusPaused    ImportStatus = "paused"
	ImportStatusCompleted ImportStatus = "completed"
	ImportStatusFailed    ImportStatus = "failed"
	ImportStatusCancelled ImportStatus = "cancelled"
)

func (e *ImportStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ImportStatus(s)
	case string:
		*e = ImportStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ImportStatus: %T", src)
	}
	return nil
}

type NullImportStatus struct {
	ImportStatus ImportStatus `json:"import_status"`
	Valid        bool         `json:"valid"` // Valid is true if ImportStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullImportStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ImportStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ImportStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullImportStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ImportStatus), nil
}

type StatsResource string

const (
	StatsResourceSummary    StatsResource = "summary"
	StatsResourceTopArtists StatsResource = "top_artists"
	StatsResourceTopAlbums  StatsResource = "top_albums"
	StatsResourceTopTracks  StatsResource = "top_tracks"
	StatsResourceActivity   StatsResource = "activity"
	StatsResourceInterest   StatsResource = "interest"
	StatsResourceClock      StatsResource = "clock"
	StatsResourceSources    StatsResource = "sources"
	StatsResourceDiscovery  StatsResource = "discovery"
	StatsResourceRewind     StatsResource = "rewind"
)

func (e *StatsResource) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StatsResource(s)
	case string:
		*e = StatsResource(s)
	default:
		return fmt.Errorf("unsupported scan type for StatsResource: %T", src)
	}
	return nil
}

type NullStatsResource struct {
	StatsResource StatsResource `json:"stats_resource"`
	Valid         bool          `json:"valid"` // Valid is true if StatsResource is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStatsResource) Scan(value interface{}) error {
	if value == nil {
		ns.StatsResource, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StatsResource.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStatsResource) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StatsResource), nil
}

type Album struct {
	ID             int64              `json:"id"`
	Name           string             `json:"name"`
	NameNormalized string             `json:"name_normalized"`
	NameRomanized  string             `json:"name_romanized"`
	ReleaseDate    pgtype.Date        `json:"release_date"`
	Description    *string            `json:"description"`
	ImageID        pgtype.UUID        `json:"image_id"`
	Pinned         bool               `json:"pinned"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type AlbumArtist struct {
	AlbumID  int64 `json:"album_id"`
	ArtistID int64 `json:"artist_id"`
	Position int16 `json:"position"`
}

type ApiKey struct {
	ID         int64              `json:"id"`
	UserID     int64              `json:"user_id"`
	Name       string             `json:"name"`
	KeyHash    string             `json:"key_hash"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Artist struct {
	ID             int64              `json:"id"`
	Name           string             `json:"name"`
	NameNormalized string             `json:"name_normalized"`
	NameRomanized  string             `json:"name_romanized"`
	Description    *string            `json:"description"`
	ImageID        pgtype.UUID        `json:"image_id"`
	Pinned         bool               `json:"pinned"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type ArtistBlacklist struct {
	UserID    int64              `json:"user_id"`
	ArtistID  int64              `json:"artist_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ClockCell struct {
	UserID      int64       `json:"user_id"`
	Day         pgtype.Date `json:"day"`
	Hour        int16       `json:"hour"`
	ListenCount int32       `json:"listen_count"`
}

type DailySongListen struct {
	UserID      int64       `json:"user_id"`
	SongID      int64       `json:"song_id"`
	Day         pgtype.Date `json:"day"`
	ListenCount int32       `json:"listen_count"`
	PlayedMs    int64       `json:"played_ms"`
}

type EntityAlias struct {
	ID         int64              `json:"id"`
	EntityType EntityType         `json:"entity_type"`
	EntityID   int64              `json:"entity_id"`
	Alias      string             `json:"alias"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type EntityGlobalStat struct {
	EntityType      EntityType         `json:"entity_type"`
	EntityID        int64              `json:"entity_id"`
	Plays           int32              `json:"plays"`
	UniqueListeners int32              `json:"unique_listeners"`
	PlayedMs        int64              `json:"played_ms"`
	FirstListenedAt pgtype.Timestamptz `json:"first_listened_at"`
}

type ImportJob struct {
	ID             int64              `json:"id"`
	UserID         int64              `json:"user_id"`
	BatchID        pgtype.UUID        `json:"batch_id"`
	Filename       string             `json:"filename"`
	Service        string             `json:"service"`
	Status         ImportStatus       `json:"status"`
	TotalItems     int32              `json:"total_items"`
	ProcessedItems int32              `json:"processed_items"`
	ImportedItems  int32              `json:"imported_items"`
	SkippedItems   int32              `json:"skipped_items"`
	FailedItems    int32              `json:"failed_items"`
	ErrorMessage   *string            `json:"error_message"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	FinishedAt     pgtype.Timestamptz `json:"finished_at"`
}

type Invite struct {
	ID        int64              `json:"id"`
	Code      string             `json:"code"`
	Name      string             `json:"name"`
	MaxUses   *int32             `json:"max_uses"`
	UsesCount int32              `json:"uses_count"`
	CreatedBy int64              `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Listen struct {
	ID               int64              `json:"id"`
	UserID           int64              `json:"user_id"`
	SongID           int64              `json:"song_id"`
	ListenedAt       pgtype.Timestamptz `json:"listened_at"`
	Client           *string            `json:"client"`
	DurationPlayedMs *int32             `json:"duration_played_ms"`
	Extra            []byte             `json:"extra"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type MergeSuggestion struct {
	ID         int64              `json:"id"`
	EntityType EntityType         `json:"entity_type"`
	LoID       int64              `json:"lo_id"`
	HiID       int64              `json:"hi_id"`
	Score      float32            `json:"score"`
	Rejected   bool               `json:"rejected"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type NowPlaying struct {
	UserID     int64              `json:"user_id"`
	SongID     int64              `json:"song_id"`
	StartedAt  pgtype.Timestamptz `json:"started_at"`
	DurationMs *int32             `json:"duration_ms"`
}

type ServerState struct {
	ID            bool `json:"id"`
	CleanShutdown bool `json:"clean_shutdown"`
}

type Session struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Song struct {
	ID             int64              `json:"id"`
	Name           string             `json:"name"`
	NameNormalized string             `json:"name_normalized"`
	NameRomanized  string             `json:"name_romanized"`
	DurationMs     *int32             `json:"duration_ms"`
	ImageID        pgtype.UUID        `json:"image_id"`
	Pinned         bool               `json:"pinned"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type SongAlbum struct {
	SongID      int64  `json:"song_id"`
	AlbumID     int64  `json:"album_id"`
	TrackNumber *int32 `json:"track_number"`
}

type SongArtist struct {
	SongID   int64 `json:"song_id"`
	ArtistID int64 `json:"artist_id"`
	Position int16 `json:"position"`
}

type Source struct {
	ID                int64              `json:"id"`
	EntityType        EntityType         `json:"entity_type"`
	EntityID          int64              `json:"entity_id"`
	SourceType        string             `json:"source_type"`
	RawUrl            *string            `json:"raw_url"`
	ExtractedID       *string            `json:"extracted_id"`
	CorrelationMethod CorrelationMethod  `json:"correlation_method"`
	Confidence        *float32           `json:"confidence"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type StatsCache struct {
	ID         int64              `json:"id"`
	UserID     *int64             `json:"user_id"`
	ArtistID   *int64             `json:"artist_id"`
	AlbumID    *int64             `json:"album_id"`
	SongID     *int64             `json:"song_id"`
	Resource   StatsResource      `json:"resource"`
	Params     []byte             `json:"params"`
	Data       []byte             `json:"data"`
	ComputedAt pgtype.Timestamptz `json:"computed_at"`
}

type User struct {
	ID           int64              `json:"id"`
	Username     string             `json:"username"`
	PasswordHash string             `json:"password_hash"`
	DisplayName  *string            `json:"display_name"`
	Description  *string            `json:"description"`
	ImageID      pgtype.UUID        `json:"image_id"`
	Public       bool               `json:"public"`
	IsAdmin      bool               `json:"is_admin"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type UserEntityFirstListen struct {
	UserID     int64              `json:"user_id"`
	EntityType EntityType         `json:"entity_type"`
	EntityID   int64              `json:"entity_id"`
	FirstAt    pgtype.Timestamptz `json:"first_at"`
}

type UserListenState struct {
	UserID         int64              `json:"user_id"`
	LastListenedAt pgtype.Timestamptz `json:"last_listened_at"`
	CurrentStreak  int32              `json:"current_streak"`
	LongestStreak  int32              `json:"longest_streak"`
}

type UserSetting struct {
	UserID   int64  `json:"user_id"`
	Settings []byte `json:"settings"`
}
