// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type CorrelationMethod string

const (
	CorrelationMethodSourceID  CorrelationMethod = "source_id"
	CorrelationMethodFuzzyName CorrelationMethod = "fuzzy_name"
	CorrelationMethodManual    CorrelationMethod = "manual"
)

func (e *CorrelationMethod) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CorrelationMethod(s)
	case string:
		*e = CorrelationMethod(s)
	default:
		return fmt.Errorf("unsupported scan type for CorrelationMethod: %T", src)
	}
	return nil
}

type NullCorrelationMethod struct {
	CorrelationMethod CorrelationMethod `json:"correlation_method"`
	Valid             bool              `json:"valid"` // Valid is true if CorrelationMethod is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCorrelationMethod) Scan(value interface{}) error {
	if value == nil {
		ns.CorrelationMethod, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CorrelationMethod.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCorrelationMethod) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CorrelationMethod), nil
}

type EntityType string

const (
	EntityTypeArtist EntityType = "artist"
	EntityTypeAlbum  EntityType = "album"
	EntityTypeSong   EntityType = "song"
)

func (e *EntityType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EntityType(s)
	case string:
		*e = EntityType(s)
	default:
		return fmt.Errorf("unsupported scan type for EntityType: %T", src)
	}
	return nil
}

type NullEntityType struct {
	EntityType EntityType `json:"entity_type"`
	Valid      bool       `json:"valid"` // Valid is true if EntityType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEntityType) Scan(value interface{}) error {
	if value == nil {
		ns.EntityType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EntityType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEntityType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EntityType), nil
}

type ImportService string

const (
	ImportServiceSpotify      ImportService = "spotify"
	ImportServiceYtmusic      ImportService = "ytmusic"
	ImportServiceLastfm       ImportService = "lastfm"
	ImportServiceListenbrainz ImportService = "listenbrainz"
	ImportServiceMaloja       ImportService = "maloja"
	ImportServiceCantoExport  ImportService = "canto_export"
)

func (e *ImportService) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ImportService(s)
	case string:
		*e = ImportService(s)
	default:
		return fmt.Errorf("unsupported scan type for ImportService: %T", src)
	}
	return nil
}

type NullImportService struct {
	ImportService ImportService `json:"import_service"`
	Valid         bool          `json:"valid"` // Valid is true if ImportService is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullImportService) Scan(value interface{}) error {
	if value == nil {
		ns.ImportService, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ImportService.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullImportService) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ImportService), nil
}

type ImportStatus string

const (
	ImportStatusQueued    ImportStatus = "queued"
	ImportStatusRunning   ImportStatus = "running"
	ImportStatusCompleted ImportStatus = "completed"
	ImportStatusFailed    ImportStatus = "failed"
	ImportStatusCancelled ImportStatus = "cancelled"
)

func (e *ImportStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ImportStatus(s)
	case string:
		*e = ImportStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ImportStatus: %T", src)
	}
	return nil
}

type NullImportStatus struct {
	ImportStatus ImportStatus `json:"import_status"`
	Valid        bool         `json:"valid"` // Valid is true if ImportStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullImportStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ImportStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ImportStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullImportStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ImportStatus), nil
}

type SourceType string

const (
	SourceTypeYtmusic     SourceType = "ytmusic"
	SourceTypeSpotify     SourceType = "spotify"
	SourceTypeBandcamp    SourceType = "bandcamp"
	SourceTypeMusicbrainz SourceType = "musicbrainz"
	SourceTypeLastfm      SourceType = "lastfm"
	SourceTypeDeezer      SourceType = "deezer"
	SourceTypeSubsonic    SourceType = "subsonic"
	SourceTypeUnknown     SourceType = "unknown"
)

func (e *SourceType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SourceType(s)
	case string:
		*e = SourceType(s)
	default:
		return fmt.Errorf("unsupported scan type for SourceType: %T", src)
	}
	return nil
}

type NullSourceType struct {
	SourceType SourceType `json:"source_type"`
	Valid      bool       `json:"valid"` // Valid is true if SourceType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSourceType) Scan(value interface{}) error {
	if value == nil {
		ns.SourceType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SourceType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSourceType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SourceType), nil
}

type Album struct {
	ID             int64              `json:"id"`
	Name           string             `json:"name"`
	NameNormalized string             `json:"name_normalized"`
	ReleaseDate    pgtype.Date        `json:"release_date"`
	Description    *string            `json:"description"`
	ImageID        pgtype.UUID        `json:"image_id"`
	Pinned         bool               `json:"pinned"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type AlbumArtist struct {
	AlbumID  int64 `json:"album_id"`
	ArtistID int64 `json:"artist_id"`
	Position int16 `json:"position"`
}

type ApiKey struct {
	ID         int64              `json:"id"`
	UserID     int64              `json:"user_id"`
	Name       string             `json:"name"`
	KeyHash    string             `json:"key_hash"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Artist struct {
	ID             int64              `json:"id"`
	Name           string             `json:"name"`
	NameNormalized string             `json:"name_normalized"`
	Description    *string            `json:"description"`
	ImageID        pgtype.UUID        `json:"image_id"`
	Pinned         bool               `json:"pinned"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type ArtistBlacklist struct {
	UserID    int64              `json:"user_id"`
	ArtistID  int64              `json:"artist_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type EntityAlias struct {
	ID         int64              `json:"id"`
	EntityType EntityType         `json:"entity_type"`
	EntityID   int64              `json:"entity_id"`
	Alias      string             `json:"alias"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type ImportJob struct {
	ID             int64              `json:"id"`
	UserID         int64              `json:"user_id"`
	BatchID        pgtype.UUID        `json:"batch_id"`
	Filename       string             `json:"filename"`
	Service        ImportService      `json:"service"`
	Status         ImportStatus       `json:"status"`
	TotalItems     int32              `json:"total_items"`
	ProcessedItems int32              `json:"processed_items"`
	ImportedItems  int32              `json:"imported_items"`
	SkippedItems   int32              `json:"skipped_items"`
	FailedItems    int32              `json:"failed_items"`
	ErrorMessage   *string            `json:"error_message"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	FinishedAt     pgtype.Timestamptz `json:"finished_at"`
}

type Invite struct {
	ID        int64              `json:"id"`
	Code      string             `json:"code"`
	Name      string             `json:"name"`
	MaxUses   *int32             `json:"max_uses"`
	UsesCount int32              `json:"uses_count"`
	CreatedBy int64              `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Listen struct {
	ID               int64              `json:"id"`
	UserID           int64              `json:"user_id"`
	SongID           int64              `json:"song_id"`
	ListenedAt       pgtype.Timestamptz `json:"listened_at"`
	Client           *string            `json:"client"`
	DurationPlayedMs *int32             `json:"duration_played_ms"`
	Extra            []byte             `json:"extra"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type NowPlaying struct {
	UserID     int64              `json:"user_id"`
	SongID     int64              `json:"song_id"`
	StartedAt  pgtype.Timestamptz `json:"started_at"`
	DurationMs *int32             `json:"duration_ms"`
}

type Session struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Song struct {
	ID             int64              `json:"id"`
	Name           string             `json:"name"`
	NameNormalized string             `json:"name_normalized"`
	DurationMs     *int32             `json:"duration_ms"`
	ImageID        pgtype.UUID        `json:"image_id"`
	Pinned         bool               `json:"pinned"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type SongAlbum struct {
	SongID      int64  `json:"song_id"`
	AlbumID     int64  `json:"album_id"`
	TrackNumber *int32 `json:"track_number"`
}

type SongArtist struct {
	SongID   int64 `json:"song_id"`
	ArtistID int64 `json:"artist_id"`
	Position int16 `json:"position"`
}

type Source struct {
	ID                int64              `json:"id"`
	EntityType        EntityType         `json:"entity_type"`
	EntityID          int64              `json:"entity_id"`
	SourceType        SourceType         `json:"source_type"`
	RawUrl            *string            `json:"raw_url"`
	ExtractedID       *string            `json:"extracted_id"`
	CorrelationMethod CorrelationMethod  `json:"correlation_method"`
	Confidence        *float32           `json:"confidence"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           int64              `json:"id"`
	Username     string             `json:"username"`
	PasswordHash string             `json:"password_hash"`
	PublicStats  bool               `json:"public_stats"`
	IsAdmin      bool               `json:"is_admin"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type UserSetting struct {
	UserID   int64  `json:"user_id"`
	Settings []byte `json:"settings"`
}
