// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: now_playing.sql

package db

import (
	"context"
)

const deleteAllNowPlaying = `-- name: DeleteAllNowPlaying :exec
DELETE FROM now_playing
`

func (q *Queries) DeleteAllNowPlaying(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllNowPlaying)
	return err
}

const getNowPlaying = `-- name: GetNowPlaying :one
SELECT user_id, song_id, started_at, duration_ms FROM now_playing
WHERE user_id = $1
  AND started_at + (COALESCE(duration_ms, 0) || ' milliseconds')::interval >= now()
`

func (q *Queries) GetNowPlaying(ctx context.Context, userID int64) (NowPlaying, error) {
	row := q.db.QueryRow(ctx, getNowPlaying, userID)
	var i NowPlaying
	err := row.Scan(
		&i.UserID,
		&i.SongID,
		&i.StartedAt,
		&i.DurationMs,
	)
	return i, err
}

const upsertNowPlaying = `-- name: UpsertNowPlaying :exec
WITH expired AS (
    DELETE FROM now_playing
    WHERE user_id != $1::bigint
      AND started_at + (COALESCE(duration_ms, 0) || ' milliseconds')::interval < now()
)
INSERT INTO now_playing (user_id, song_id, started_at, duration_ms)
VALUES ($1::bigint, $2::bigint, now(), $3::integer)
ON CONFLICT (user_id) DO UPDATE SET
    song_id = excluded.song_id,
    started_at = now(),
    duration_ms = excluded.duration_ms
`

type UpsertNowPlayingParams struct {
	UserID     int64 `json:"user_id"`
	SongID     int64 `json:"song_id"`
	DurationMs int32 `json:"duration_ms"`
}

func (q *Queries) UpsertNowPlaying(ctx context.Context, arg UpsertNowPlayingParams) error {
	_, err := q.db.Exec(ctx, upsertNowPlaying, arg.UserID, arg.SongID, arg.DurationMs)
	return err
}
