// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rollup.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bumpEntityGlobalUniqueListeners = `-- name: BumpEntityGlobalUniqueListeners :exec
INSERT INTO entity_global_stats (entity_type, entity_id, unique_listeners)
SELECT unnest($1::text[])::entity_type,
       unnest($2::bigint[]),
       unnest($3::int[])
ON CONFLICT (entity_type, entity_id) DO UPDATE SET
    unique_listeners = entity_global_stats.unique_listeners + excluded.unique_listeners
`

type BumpEntityGlobalUniqueListenersParams struct {
	EntityTypes []string `json:"entity_types"`
	EntityIds   []int64  `json:"entity_ids"`
	Counts      []int32  `json:"counts"`
}

// entity_types/entity_ids/counts must already be aggregated (one row per entity, count =
// how many of that entity's rows InsertFirstListens actually returned in this batch).
func (q *Queries) BumpEntityGlobalUniqueListeners(ctx context.Context, arg BumpEntityGlobalUniqueListenersParams) error {
	_, err := q.db.Exec(ctx, bumpEntityGlobalUniqueListeners, arg.EntityTypes, arg.EntityIds, arg.Counts)
	return err
}

const computeUserStreak = `-- name: ComputeUserStreak :one
WITH days AS (
    SELECT DISTINCT day FROM daily_song_listens WHERE user_id = $1::bigint
),
day_groups AS (SELECT day, day - (row_number() OVER (ORDER BY day)) * INTERVAL '1 day' AS g FROM days),
streaks AS (SELECT g, count(*) AS len, max(day) AS last_day FROM day_groups GROUP BY g)
SELECT
    coalesce((SELECT max(len) FROM streaks), 0)::bigint AS longest_streak,
    coalesce((SELECT len FROM streaks WHERE last_day >= (now() AT TIME ZONE 'UTC')::date - 1 ORDER BY last_day DESC LIMIT 1), 0)::bigint AS current_streak,
    (SELECT max(listened_at) FROM listens WHERE user_id = $1::bigint)::timestamptz AS last_listened_at
`

type ComputeUserStreakRow struct {
	LongestStreak  int64              `json:"longest_streak"`
	CurrentStreak  int64              `json:"current_streak"`
	LastListenedAt pgtype.Timestamptz `json:"last_listened_at"`
}

// All-time streak recompute from daily_song_listens, used to reconcile user_listen_state
// after a bulk import (whose entries arrive out of chronological order) and by the admin
// full-recompute command.
func (q *Queries) ComputeUserStreak(ctx context.Context, userID int64) (ComputeUserStreakRow, error) {
	row := q.db.QueryRow(ctx, computeUserStreak, userID)
	var i ComputeUserStreakRow
	err := row.Scan(&i.LongestStreak, &i.CurrentStreak, &i.LastListenedAt)
	return i, err
}

const getUserListenStates = `-- name: GetUserListenStates :many
SELECT user_id, last_listened_at, current_streak, longest_streak FROM user_listen_state WHERE user_id = ANY($1::bigint[])
`

func (q *Queries) GetUserListenStates(ctx context.Context, userIds []int64) ([]UserListenState, error) {
	rows, err := q.db.Query(ctx, getUserListenStates, userIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserListenState
	for rows.Next() {
		var i UserListenState
		if err := rows.Scan(
			&i.UserID,
			&i.LastListenedAt,
			&i.CurrentStreak,
			&i.LongestStreak,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertFirstListens = `-- name: InsertFirstListens :many
INSERT INTO user_entity_first_listen (user_id, entity_type, entity_id, first_at)
SELECT unnest($1::bigint[]),
       unnest($2::text[])::entity_type,
       unnest($3::bigint[]),
       unnest($4::timestamptz[])
ON CONFLICT (user_id, entity_type, entity_id) DO NOTHING
RETURNING user_id, entity_type, entity_id
`

type InsertFirstListensParams struct {
	UserIds     []int64              `json:"user_ids"`
	EntityTypes []string             `json:"entity_types"`
	EntityIds   []int64              `json:"entity_ids"`
	FirstAts    []pgtype.Timestamptz `json:"first_ats"`
}

type InsertFirstListensRow struct {
	UserID     int64      `json:"user_id"`
	EntityType EntityType `json:"entity_type"`
	EntityID   int64      `json:"entity_id"`
}

// Candidates must already be deduped to one row per (user_id, entity_type, entity_id),
// keeping the earliest first_at, before calling this. Returned rows are genuine first
// sightings (the discoveries in this batch); rows silently dropped by DO NOTHING already existed.
func (q *Queries) InsertFirstListens(ctx context.Context, arg InsertFirstListensParams) ([]InsertFirstListensRow, error) {
	rows, err := q.db.Query(ctx, insertFirstListens,
		arg.UserIds,
		arg.EntityTypes,
		arg.EntityIds,
		arg.FirstAts,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InsertFirstListensRow
	for rows.Next() {
		var i InsertFirstListensRow
		if err := rows.Scan(&i.UserID, &i.EntityType, &i.EntityID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rebuildClockCells = `-- name: RebuildClockCells :exec
WITH eligible_listens AS (
    SELECT l.user_id, l.song_id, l.listened_at,
           coalesce(l.duration_played_ms, s.duration_ms, 0) AS played_ms
    FROM listens l
    JOIN songs s ON s.id = l.song_id
    WHERE (s.duration_ms IS NULL OR s.duration_ms <= 0
           OR coalesce(l.duration_played_ms, s.duration_ms, 0) * 2 >= s.duration_ms
           OR coalesce(l.duration_played_ms, s.duration_ms, 0) >= 240000)
)
INSERT INTO clock_cells (user_id, day, hour, listen_count)
SELECT user_id, (listened_at AT TIME ZONE 'UTC')::date, extract(hour FROM listened_at AT TIME ZONE 'UTC')::smallint, count(*)::int
FROM eligible_listens
GROUP BY user_id, (listened_at AT TIME ZONE 'UTC')::date, extract(hour FROM listened_at AT TIME ZONE 'UTC')
`

func (q *Queries) RebuildClockCells(ctx context.Context) error {
	_, err := q.db.Exec(ctx, rebuildClockCells)
	return err
}

const rebuildDailySongListens = `-- name: RebuildDailySongListens :exec
WITH eligible_listens AS (
    SELECT l.user_id, l.song_id, l.listened_at,
           coalesce(l.duration_played_ms, s.duration_ms, 0) AS played_ms
    FROM listens l
    JOIN songs s ON s.id = l.song_id
    WHERE (s.duration_ms IS NULL OR s.duration_ms <= 0
           OR coalesce(l.duration_played_ms, s.duration_ms, 0) * 2 >= s.duration_ms
           OR coalesce(l.duration_played_ms, s.duration_ms, 0) >= 240000)
)
INSERT INTO daily_song_listens (user_id, song_id, day, listen_count, played_ms)
SELECT user_id, song_id, (listened_at AT TIME ZONE 'UTC')::date, count(*)::int, coalesce(sum(played_ms), 0)::bigint
FROM eligible_listens
GROUP BY user_id, song_id, (listened_at AT TIME ZONE 'UTC')::date
`

// Mirrors rollup.Eligible's threshold exactly.
func (q *Queries) RebuildDailySongListens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, rebuildDailySongListens)
	return err
}

const rebuildEntityFirstListens = `-- name: RebuildEntityFirstListens :exec
WITH eligible_listens AS (
    SELECT l.user_id, l.song_id, l.listened_at,
           coalesce(l.duration_played_ms, s.duration_ms, 0) AS played_ms
    FROM listens l
    JOIN songs s ON s.id = l.song_id
    WHERE (s.duration_ms IS NULL OR s.duration_ms <= 0
           OR coalesce(l.duration_played_ms, s.duration_ms, 0) * 2 >= s.duration_ms
           OR coalesce(l.duration_played_ms, s.duration_ms, 0) >= 240000)
)
INSERT INTO user_entity_first_listen (user_id, entity_type, entity_id, first_at)
SELECT user_id, 'song'::entity_type, song_id, min(listened_at) FROM eligible_listens GROUP BY user_id, song_id
UNION ALL
SELECT el.user_id, 'album'::entity_type, sa.album_id, min(el.listened_at)
FROM eligible_listens el JOIN song_albums sa ON sa.song_id = el.song_id
GROUP BY el.user_id, sa.album_id
UNION ALL
SELECT el.user_id, 'artist'::entity_type, sar.artist_id, min(el.listened_at)
FROM eligible_listens el JOIN song_artists sar ON sar.song_id = el.song_id
GROUP BY el.user_id, sar.artist_id
`

func (q *Queries) RebuildEntityFirstListens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, rebuildEntityFirstListens)
	return err
}

const rebuildEntityGlobalStats = `-- name: RebuildEntityGlobalStats :exec
WITH eligible_listens AS (
    SELECT l.user_id, l.song_id, l.listened_at,
           coalesce(l.duration_played_ms, s.duration_ms, 0) AS played_ms
    FROM listens l
    JOIN songs s ON s.id = l.song_id
    WHERE (s.duration_ms IS NULL OR s.duration_ms <= 0
           OR coalesce(l.duration_played_ms, s.duration_ms, 0) * 2 >= s.duration_ms
           OR coalesce(l.duration_played_ms, s.duration_ms, 0) >= 240000)
)
INSERT INTO entity_global_stats (entity_type, entity_id, plays, unique_listeners, played_ms, first_listened_at)
SELECT entity_type, entity_id, count(*)::int AS plays, count(DISTINCT user_id)::int AS unique_listeners,
       coalesce(sum(played_ms), 0)::bigint AS played_ms, min(first_at)
FROM (
    SELECT user_id, 'song'::entity_type AS entity_type, song_id AS entity_id, listened_at AS first_at, played_ms FROM eligible_listens
    UNION ALL
    SELECT el.user_id, 'album'::entity_type, sa.album_id, el.listened_at, el.played_ms
    FROM eligible_listens el JOIN song_albums sa ON sa.song_id = el.song_id
    UNION ALL
    SELECT el.user_id, 'artist'::entity_type, sar.artist_id, el.listened_at, el.played_ms
    FROM eligible_listens el JOIN song_artists sar ON sar.song_id = el.song_id
) t
GROUP BY entity_type, entity_id
`

func (q *Queries) RebuildEntityGlobalStats(ctx context.Context) error {
	_, err := q.db.Exec(ctx, rebuildEntityGlobalStats)
	return err
}

const rebuildUserListenStates = `-- name: RebuildUserListenStates :exec
WITH days AS (
    SELECT DISTINCT user_id, day FROM daily_song_listens
),
day_groups AS (
    SELECT user_id, day, day - (row_number() OVER (PARTITION BY user_id ORDER BY day)) * INTERVAL '1 day' AS g
    FROM days
),
streaks AS (SELECT user_id, g, count(*) AS len, max(day) AS last_day FROM day_groups GROUP BY user_id, g),
longest AS (SELECT user_id, max(len) AS longest_streak FROM streaks GROUP BY user_id),
current AS (
    SELECT DISTINCT ON (user_id) user_id, len AS current_streak
    FROM streaks
    WHERE last_day >= (now() AT TIME ZONE 'UTC')::date - 1
    ORDER BY user_id, last_day DESC
),
last_at AS (SELECT user_id, max(listened_at) AS last_listened_at FROM listens GROUP BY user_id)
INSERT INTO user_listen_state (user_id, last_listened_at, current_streak, longest_streak)
SELECT la.user_id, la.last_listened_at, coalesce(c.current_streak, 0)::int, coalesce(l.longest_streak, 0)::int
FROM last_at la
LEFT JOIN longest l ON l.user_id = la.user_id
LEFT JOIN current c ON c.user_id = la.user_id
`

// Must run after RebuildDailySongListens (reuses daily_song_listens for the day-grain streak scan).
func (q *Queries) RebuildUserListenStates(ctx context.Context) error {
	_, err := q.db.Exec(ctx, rebuildUserListenStates)
	return err
}

const rollupActivityBuckets = `-- name: RollupActivityBuckets :many
WITH scoped AS (
    SELECT user_id, song_id, day, listen_count, played_ms FROM daily_song_listens dsl
    WHERE ($4::bigint IS NULL OR dsl.user_id = $4::bigint)
      AND ($5::bigint IS NULL OR EXISTS (
            SELECT 1 FROM song_artists sar WHERE sar.song_id = dsl.song_id AND sar.artist_id = $5::bigint))
      AND ($6::bigint IS NULL OR EXISTS (
            SELECT 1 FROM song_albums sa2 WHERE sa2.song_id = dsl.song_id AND sa2.album_id = $6::bigint))
      AND ($7::bigint IS NULL OR dsl.song_id = $7::bigint)
)
SELECT gs.bucket, coalesce(sum(sc.listen_count), 0)::bigint AS listen_count,
       (coalesce(sum(sc.played_ms), 0)::float8 / 60000.0)::float8 AS minutes_listened
FROM generate_series($1::timestamptz, $2::timestamptz, $3::interval) AS gs(bucket)
LEFT JOIN scoped sc
  ON (sc.day::timestamp AT TIME ZONE 'UTC') >= gs.bucket AND (sc.day::timestamp AT TIME ZONE 'UTC') < gs.bucket + $3::interval
GROUP BY gs.bucket ORDER BY gs.bucket
`

type RollupActivityBucketsParams struct {
	FromTime pgtype.Timestamptz `json:"from_time"`
	ToTime   pgtype.Timestamptz `json:"to_time"`
	Step     pgtype.Interval    `json:"step"`
	UserID   *int64             `json:"user_id"`
	ArtistID *int64             `json:"artist_id"`
	AlbumID  *int64             `json:"album_id"`
	SongID   *int64             `json:"song_id"`
}

type RollupActivityBucketsRow struct {
	Bucket          interface{} `json:"bucket"`
	ListenCount     int64       `json:"listen_count"`
	MinutesListened float64     `json:"minutes_listened"`
}

func (q *Queries) RollupActivityBuckets(ctx context.Context, arg RollupActivityBucketsParams) ([]RollupActivityBucketsRow, error) {
	rows, err := q.db.Query(ctx, rollupActivityBuckets,
		arg.FromTime,
		arg.ToTime,
		arg.Step,
		arg.UserID,
		arg.ArtistID,
		arg.AlbumID,
		arg.SongID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RollupActivityBucketsRow
	for rows.Next() {
		var i RollupActivityBucketsRow
		if err := rows.Scan(&i.Bucket, &i.ListenCount, &i.MinutesListened); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rollupAvgSessionLengthMs = `-- name: RollupAvgSessionLengthMs :one
WITH scoped AS (
    SELECT l.id, l.user_id, l.song_id, l.listened_at, l.client, l.duration_played_ms, l.extra, l.created_at FROM listens l
    WHERE l.user_id = $1::bigint
      AND l.listened_at >= $2::timestamptz
      AND l.listened_at < $3::timestamptz
),
prev_listen AS (SELECT listened_at, lag(listened_at) OVER (ORDER BY listened_at) AS prev_at FROM scoped),
session_starts AS (
    SELECT listened_at, CASE WHEN prev_at IS NULL OR listened_at - prev_at > INTERVAL '5 minutes' THEN 1 ELSE 0 END AS is_new
    FROM prev_listen
),
sessions AS (SELECT listened_at, sum(is_new) OVER (ORDER BY listened_at) AS session_id FROM session_starts),
session_spans AS (SELECT session_id, min(listened_at) AS start_at, max(listened_at) AS end_at FROM sessions GROUP BY session_id)
SELECT coalesce(avg(extract(epoch FROM end_at) - extract(epoch FROM start_at)) * 1000, 0)::float8 AS avg_session_length_ms FROM session_spans
`

type RollupAvgSessionLengthMsParams struct {
	UserID   int64              `json:"user_id"`
	FromTime pgtype.Timestamptz `json:"from_time"`
	ToTime   pgtype.Timestamptz `json:"to_time"`
}

// Sessions need exact listen timestamps, which day-grain rollups can't reconstruct, so
// this stays a live query over listens (bounded to one user + range, index-backed).
func (q *Queries) RollupAvgSessionLengthMs(ctx context.Context, arg RollupAvgSessionLengthMsParams) (float64, error) {
	row := q.db.QueryRow(ctx, rollupAvgSessionLengthMs, arg.UserID, arg.FromTime, arg.ToTime)
	var avg_session_length_ms float64
	err := row.Scan(&avg_session_length_ms)
	return avg_session_length_ms, err
}

const rollupClockGrid = `-- name: RollupClockGrid :many
SELECT extract(dow FROM local_ts)::smallint AS day_of_week,
       extract(hour FROM local_ts)::smallint AS hour,
       sum(listen_count)::bigint AS listen_count
FROM (
    SELECT (day::timestamp + hour * interval '1 hour') AT TIME ZONE 'UTC' AT TIME ZONE $1::text AS local_ts,
           listen_count
    FROM clock_cells
    WHERE ($2::bigint IS NULL OR user_id = $2::bigint)
      AND day >= $3::date
      AND day < $4::date
) shifted
GROUP BY 1, 2
`

type RollupClockGridParams struct {
	Tz      string      `json:"tz"`
	UserID  *int64      `json:"user_id"`
	FromDay pgtype.Date `json:"from_day"`
	ToDay   pgtype.Date `json:"to_day"`
}

type RollupClockGridRow struct {
	DayOfWeek   int16 `json:"day_of_week"`
	Hour        int16 `json:"hour"`
	ListenCount int64 `json:"listen_count"`
}

// clock_cells stores day/hour in UTC; shift into tz here so hours reflect the caller's local time.
func (q *Queries) RollupClockGrid(ctx context.Context, arg RollupClockGridParams) ([]RollupClockGridRow, error) {
	rows, err := q.db.Query(ctx, rollupClockGrid,
		arg.Tz,
		arg.UserID,
		arg.FromDay,
		arg.ToDay,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RollupClockGridRow
	for rows.Next() {
		var i RollupClockGridRow
		if err := rows.Scan(&i.DayOfWeek, &i.Hour, &i.ListenCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rollupDiscoveryBuckets = `-- name: RollupDiscoveryBuckets :many
WITH buckets AS (
    SELECT bucket FROM generate_series($1::timestamptz, $2::timestamptz, $3::interval) AS gs(bucket)
),
totals AS (
    SELECT b.bucket, coalesce(sum(dsl.listen_count), 0)::bigint AS total
    FROM buckets b
    LEFT JOIN daily_song_listens dsl
      ON (dsl.day::timestamp AT TIME ZONE 'UTC') >= b.bucket AND (dsl.day::timestamp AT TIME ZONE 'UTC') < b.bucket + $3::interval
      AND ($4::bigint IS NULL OR dsl.user_id = $4::bigint)
    GROUP BY b.bucket
),
discoveries AS (
    SELECT b.bucket, count(fs.first_at)::bigint AS discoveries
    FROM buckets b
    LEFT JOIN user_entity_first_listen fs
      ON fs.entity_type = 'song' AND fs.first_at >= b.bucket AND fs.first_at < b.bucket + $3::interval
      AND ($4::bigint IS NULL OR fs.user_id = $4::bigint)
    GROUP BY b.bucket
)
SELECT t.bucket, t.total, d.discoveries
FROM totals t JOIN discoveries d ON d.bucket = t.bucket
ORDER BY t.bucket
`

type RollupDiscoveryBucketsParams struct {
	FromTime pgtype.Timestamptz `json:"from_time"`
	ToTime   pgtype.Timestamptz `json:"to_time"`
	Step     pgtype.Interval    `json:"step"`
	UserID   *int64             `json:"user_id"`
}

type RollupDiscoveryBucketsRow struct {
	Bucket      interface{} `json:"bucket"`
	Total       int64       `json:"total"`
	Discoveries int64       `json:"discoveries"`
}

func (q *Queries) RollupDiscoveryBuckets(ctx context.Context, arg RollupDiscoveryBucketsParams) ([]RollupDiscoveryBucketsRow, error) {
	rows, err := q.db.Query(ctx, rollupDiscoveryBuckets,
		arg.FromTime,
		arg.ToTime,
		arg.Step,
		arg.UserID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RollupDiscoveryBucketsRow
	for rows.Next() {
		var i RollupDiscoveryBucketsRow
		if err := rows.Scan(&i.Bucket, &i.Total, &i.Discoveries); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rollupEntitySummary = `-- name: RollupEntitySummary :one
SELECT plays, unique_listeners, (played_ms::float8 / 60000.0)::float8 AS minutes_listened, first_listened_at
FROM entity_global_stats
WHERE entity_type = $1::entity_type AND entity_id = $2::bigint
`

type RollupEntitySummaryParams struct {
	EntityType EntityType `json:"entity_type"`
	EntityID   int64      `json:"entity_id"`
}

type RollupEntitySummaryRow struct {
	Plays           int32              `json:"plays"`
	UniqueListeners int32              `json:"unique_listeners"`
	MinutesListened float64            `json:"minutes_listened"`
	FirstListenedAt pgtype.Timestamptz `json:"first_listened_at"`
}

func (q *Queries) RollupEntitySummary(ctx context.Context, arg RollupEntitySummaryParams) (RollupEntitySummaryRow, error) {
	row := q.db.QueryRow(ctx, rollupEntitySummary, arg.EntityType, arg.EntityID)
	var i RollupEntitySummaryRow
	err := row.Scan(
		&i.Plays,
		&i.UniqueListeners,
		&i.MinutesListened,
		&i.FirstListenedAt,
	)
	return i, err
}

const rollupLongestStreak = `-- name: RollupLongestStreak :one
WITH days AS (
    SELECT DISTINCT day FROM daily_song_listens
    WHERE user_id = $1::bigint AND day >= $2::date AND day < $3::date
),
day_groups AS (SELECT day, day - (row_number() OVER (ORDER BY day)) * INTERVAL '1 day' AS g FROM days),
streaks AS (SELECT count(*) AS len FROM day_groups GROUP BY g)
SELECT coalesce(max(len), 0)::bigint AS longest_streak FROM streaks
`

type RollupLongestStreakParams struct {
	UserID  int64       `json:"user_id"`
	FromDay pgtype.Date `json:"from_day"`
	ToDay   pgtype.Date `json:"to_day"`
}

// Range-scoped, per-user only (a "streak" spanning every user isn't a meaningful concept).
func (q *Queries) RollupLongestStreak(ctx context.Context, arg RollupLongestStreakParams) (int64, error) {
	row := q.db.QueryRow(ctx, rollupLongestStreak, arg.UserID, arg.FromDay, arg.ToDay)
	var longest_streak int64
	err := row.Scan(&longest_streak)
	return longest_streak, err
}

const rollupNewEntityCounts = `-- name: RollupNewEntityCounts :one
SELECT
    count(*) FILTER (WHERE entity_type = 'song')::bigint AS new_tracks,
    count(*) FILTER (WHERE entity_type = 'album')::bigint AS new_albums,
    count(*) FILTER (WHERE entity_type = 'artist')::bigint AS new_artists
FROM user_entity_first_listen
WHERE user_id = $1::bigint
  AND first_at >= $2::timestamptz
  AND first_at < $3::timestamptz
`

type RollupNewEntityCountsParams struct {
	UserID   int64              `json:"user_id"`
	FromTime pgtype.Timestamptz `json:"from_time"`
	ToTime   pgtype.Timestamptz `json:"to_time"`
}

type RollupNewEntityCountsRow struct {
	NewTracks  int64 `json:"new_tracks"`
	NewAlbums  int64 `json:"new_albums"`
	NewArtists int64 `json:"new_artists"`
}

func (q *Queries) RollupNewEntityCounts(ctx context.Context, arg RollupNewEntityCountsParams) (RollupNewEntityCountsRow, error) {
	row := q.db.QueryRow(ctx, rollupNewEntityCounts, arg.UserID, arg.FromTime, arg.ToTime)
	var i RollupNewEntityCountsRow
	err := row.Scan(&i.NewTracks, &i.NewAlbums, &i.NewArtists)
	return i, err
}

const rollupSummaryStats = `-- name: RollupSummaryStats :one
WITH scoped AS (
    SELECT user_id, song_id, day, listen_count, played_ms FROM daily_song_listens dsl
    WHERE ($1::bigint IS NULL OR dsl.user_id = $1::bigint)
      AND dsl.day >= $2::date
      AND dsl.day < $3::date
)
SELECT
    (SELECT coalesce(sum(listen_count), 0) FROM scoped)::bigint AS listen_count,
    (SELECT count(DISTINCT song_id) FROM scoped)::bigint AS unique_tracks,
    (SELECT count(DISTINCT sa.album_id) FROM scoped s JOIN song_albums sa ON sa.song_id = s.song_id)::bigint AS unique_albums,
    (SELECT count(DISTINCT sar.artist_id) FROM scoped s JOIN song_artists sar ON sar.song_id = s.song_id)::bigint AS unique_artists,
    ((SELECT coalesce(sum(played_ms), 0) FROM scoped)::float8 / 60000.0)::float8 AS minutes_listened,
    (SELECT count(DISTINCT day) FROM scoped)::bigint AS days_active
`

type RollupSummaryStatsParams struct {
	UserID  *int64      `json:"user_id"`
	FromDay pgtype.Date `json:"from_day"`
	ToDay   pgtype.Date `json:"to_day"`
}

type RollupSummaryStatsRow struct {
	ListenCount     int64   `json:"listen_count"`
	UniqueTracks    int64   `json:"unique_tracks"`
	UniqueAlbums    int64   `json:"unique_albums"`
	UniqueArtists   int64   `json:"unique_artists"`
	MinutesListened float64 `json:"minutes_listened"`
	DaysActive      int64   `json:"days_active"`
}

func (q *Queries) RollupSummaryStats(ctx context.Context, arg RollupSummaryStatsParams) (RollupSummaryStatsRow, error) {
	row := q.db.QueryRow(ctx, rollupSummaryStats, arg.UserID, arg.FromDay, arg.ToDay)
	var i RollupSummaryStatsRow
	err := row.Scan(
		&i.ListenCount,
		&i.UniqueTracks,
		&i.UniqueAlbums,
		&i.UniqueArtists,
		&i.MinutesListened,
		&i.DaysActive,
	)
	return i, err
}

const rollupTopAlbums = `-- name: RollupTopAlbums :many
WITH scoped AS (
    SELECT user_id, song_id, day, listen_count, played_ms FROM daily_song_listens dsl
    WHERE ($1::bigint IS NULL OR dsl.user_id = $1::bigint)
      AND dsl.day >= $5::date
      AND dsl.day < $6::date
)
SELECT sa.album_id, al.name, al.image_id, sum(s.listen_count)::bigint AS listen_count,
       (sum(s.played_ms)::float8 / 60000.0)::float8 AS minutes_listened,
       coalesce((SELECT ar.id FROM album_artists aa2 JOIN artists ar ON ar.id = aa2.artist_id
        WHERE aa2.album_id = sa.album_id ORDER BY aa2.position LIMIT 1), 0)::bigint AS artist_id,
       coalesce((SELECT ar.name FROM album_artists aa2 JOIN artists ar ON ar.id = aa2.artist_id
        WHERE aa2.album_id = sa.album_id ORDER BY aa2.position LIMIT 1), '')::text AS artist_name,
       EXISTS (
         SELECT 1 FROM album_artists aa3 JOIN artist_blacklist bl ON bl.artist_id = aa3.artist_id
         WHERE aa3.album_id = sa.album_id AND bl.user_id = $1::bigint
       ) AS blacklisted
FROM scoped s
JOIN song_albums sa ON sa.song_id = s.song_id
JOIN albums al ON al.id = sa.album_id
GROUP BY sa.album_id, al.name, al.image_id
ORDER BY blacklisted ASC,
    (CASE WHEN $2::text = 'minutes' THEN sum(s.played_ms)::float8 ELSE sum(s.listen_count)::float8 END) DESC,
    al.name
LIMIT $4::int OFFSET $3::int
`

type RollupTopAlbumsParams struct {
	UserID    *int64      `json:"user_id"`
	SortBy    string      `json:"sort_by"`
	RowOffset int32       `json:"row_offset"`
	MaxRows   int32       `json:"max_rows"`
	FromDay   pgtype.Date `json:"from_day"`
	ToDay     pgtype.Date `json:"to_day"`
}

type RollupTopAlbumsRow struct {
	AlbumID         int64       `json:"album_id"`
	Name            string      `json:"name"`
	ImageID         pgtype.UUID `json:"image_id"`
	ListenCount     int64       `json:"listen_count"`
	MinutesListened float64     `json:"minutes_listened"`
	ArtistID        int64       `json:"artist_id"`
	ArtistName      string      `json:"artist_name"`
	Blacklisted     bool        `json:"blacklisted"`
}

func (q *Queries) RollupTopAlbums(ctx context.Context, arg RollupTopAlbumsParams) ([]RollupTopAlbumsRow, error) {
	rows, err := q.db.Query(ctx, rollupTopAlbums,
		arg.UserID,
		arg.SortBy,
		arg.RowOffset,
		arg.MaxRows,
		arg.FromDay,
		arg.ToDay,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RollupTopAlbumsRow
	for rows.Next() {
		var i RollupTopAlbumsRow
		if err := rows.Scan(
			&i.AlbumID,
			&i.Name,
			&i.ImageID,
			&i.ListenCount,
			&i.MinutesListened,
			&i.ArtistID,
			&i.ArtistName,
			&i.Blacklisted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rollupTopArtists = `-- name: RollupTopArtists :many
WITH scoped AS (
    SELECT user_id, song_id, day, listen_count, played_ms FROM daily_song_listens dsl
    WHERE ($1::bigint IS NULL OR dsl.user_id = $1::bigint)
      AND dsl.day >= $5::date
      AND dsl.day < $6::date
)
SELECT sar.artist_id, a.name, a.image_id, sum(s.listen_count)::bigint AS listen_count,
       (sum(s.played_ms)::float8 / 60000.0)::float8 AS minutes_listened,
       EXISTS (
         SELECT 1 FROM artist_blacklist bl
         WHERE bl.user_id = $1::bigint AND bl.artist_id = sar.artist_id
       ) AS blacklisted
FROM scoped s
JOIN song_artists sar ON sar.song_id = s.song_id
JOIN artists a ON a.id = sar.artist_id
GROUP BY sar.artist_id, a.name, a.image_id
ORDER BY blacklisted ASC,
    (CASE WHEN $2::text = 'minutes' THEN sum(s.played_ms)::float8 ELSE sum(s.listen_count)::float8 END) DESC,
    a.name
LIMIT $4::int OFFSET $3::int
`

type RollupTopArtistsParams struct {
	UserID    *int64      `json:"user_id"`
	SortBy    string      `json:"sort_by"`
	RowOffset int32       `json:"row_offset"`
	MaxRows   int32       `json:"max_rows"`
	FromDay   pgtype.Date `json:"from_day"`
	ToDay     pgtype.Date `json:"to_day"`
}

type RollupTopArtistsRow struct {
	ArtistID        int64       `json:"artist_id"`
	Name            string      `json:"name"`
	ImageID         pgtype.UUID `json:"image_id"`
	ListenCount     int64       `json:"listen_count"`
	MinutesListened float64     `json:"minutes_listened"`
	Blacklisted     bool        `json:"blacklisted"`
}

// blacklisted is always false for the global scope (user_id NULL): blacklisting is a personal
// preference, not something one user's opinion should reorder for everyone else.
func (q *Queries) RollupTopArtists(ctx context.Context, arg RollupTopArtistsParams) ([]RollupTopArtistsRow, error) {
	rows, err := q.db.Query(ctx, rollupTopArtists,
		arg.UserID,
		arg.SortBy,
		arg.RowOffset,
		arg.MaxRows,
		arg.FromDay,
		arg.ToDay,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RollupTopArtistsRow
	for rows.Next() {
		var i RollupTopArtistsRow
		if err := rows.Scan(
			&i.ArtistID,
			&i.Name,
			&i.ImageID,
			&i.ListenCount,
			&i.MinutesListened,
			&i.Blacklisted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rollupTopDay = `-- name: RollupTopDay :one
SELECT day, sum(listen_count)::bigint AS listen_count
FROM daily_song_listens
WHERE user_id = $1::bigint
  AND day >= $2::date
  AND day < $3::date
GROUP BY day
ORDER BY listen_count DESC, day
LIMIT 1
`

type RollupTopDayParams struct {
	UserID  int64       `json:"user_id"`
	FromDay pgtype.Date `json:"from_day"`
	ToDay   pgtype.Date `json:"to_day"`
}

type RollupTopDayRow struct {
	Day         pgtype.Date `json:"day"`
	ListenCount int64       `json:"listen_count"`
}

func (q *Queries) RollupTopDay(ctx context.Context, arg RollupTopDayParams) (RollupTopDayRow, error) {
	row := q.db.QueryRow(ctx, rollupTopDay, arg.UserID, arg.FromDay, arg.ToDay)
	var i RollupTopDayRow
	err := row.Scan(&i.Day, &i.ListenCount)
	return i, err
}

const rollupTopTracks = `-- name: RollupTopTracks :many
WITH scoped AS (
    SELECT user_id, song_id, day, listen_count, played_ms FROM daily_song_listens dsl
    WHERE ($1::bigint IS NULL OR dsl.user_id = $1::bigint)
      AND dsl.day >= $5::date
      AND dsl.day < $6::date
      AND ($7::bigint IS NULL OR EXISTS (
            SELECT 1 FROM song_artists sar WHERE sar.song_id = dsl.song_id AND sar.artist_id = $7::bigint))
      AND ($8::bigint IS NULL OR EXISTS (
            SELECT 1 FROM song_albums sa2 WHERE sa2.song_id = dsl.song_id AND sa2.album_id = $8::bigint))
)
SELECT s.song_id, sg.name, sg.image_id, sum(s.listen_count)::bigint AS listen_count,
       (sum(s.played_ms)::float8 / 60000.0)::float8 AS minutes_listened,
       coalesce((SELECT ar.id FROM song_artists sar2 JOIN artists ar ON ar.id = sar2.artist_id
        WHERE sar2.song_id = s.song_id ORDER BY sar2.position LIMIT 1), 0)::bigint AS artist_id,
       coalesce((SELECT ar.name FROM song_artists sar2 JOIN artists ar ON ar.id = sar2.artist_id
        WHERE sar2.song_id = s.song_id ORDER BY sar2.position LIMIT 1), '')::text AS artist_name,
       coalesce((SELECT al.id FROM song_albums sal JOIN albums al ON al.id = sal.album_id
        WHERE sal.song_id = s.song_id ORDER BY sal.track_number LIMIT 1), 0)::bigint AS album_id,
       coalesce((SELECT al.name FROM song_albums sal JOIN albums al ON al.id = sal.album_id
        WHERE sal.song_id = s.song_id ORDER BY sal.track_number LIMIT 1), '')::text AS album_name,
       EXISTS (
         SELECT 1 FROM song_artists sar3 JOIN artist_blacklist bl ON bl.artist_id = sar3.artist_id
         WHERE sar3.song_id = s.song_id AND bl.user_id = $1::bigint
       ) AS blacklisted
FROM scoped s
JOIN songs sg ON sg.id = s.song_id
GROUP BY s.song_id, sg.name, sg.image_id
ORDER BY blacklisted ASC,
    (CASE WHEN $2::text = 'minutes' THEN sum(s.played_ms)::float8 ELSE sum(s.listen_count)::float8 END) DESC,
    sg.name
LIMIT $4::int OFFSET $3::int
`

type RollupTopTracksParams struct {
	UserID    *int64      `json:"user_id"`
	SortBy    string      `json:"sort_by"`
	RowOffset int32       `json:"row_offset"`
	MaxRows   int32       `json:"max_rows"`
	FromDay   pgtype.Date `json:"from_day"`
	ToDay     pgtype.Date `json:"to_day"`
	ArtistID  *int64      `json:"artist_id"`
	AlbumID   *int64      `json:"album_id"`
}

type RollupTopTracksRow struct {
	SongID          int64       `json:"song_id"`
	Name            string      `json:"name"`
	ImageID         pgtype.UUID `json:"image_id"`
	ListenCount     int64       `json:"listen_count"`
	MinutesListened float64     `json:"minutes_listened"`
	ArtistID        int64       `json:"artist_id"`
	ArtistName      string      `json:"artist_name"`
	AlbumID         int64       `json:"album_id"`
	AlbumName       string      `json:"album_name"`
	Blacklisted     bool        `json:"blacklisted"`
}

func (q *Queries) RollupTopTracks(ctx context.Context, arg RollupTopTracksParams) ([]RollupTopTracksRow, error) {
	rows, err := q.db.Query(ctx, rollupTopTracks,
		arg.UserID,
		arg.SortBy,
		arg.RowOffset,
		arg.MaxRows,
		arg.FromDay,
		arg.ToDay,
		arg.ArtistID,
		arg.AlbumID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RollupTopTracksRow
	for rows.Next() {
		var i RollupTopTracksRow
		if err := rows.Scan(
			&i.SongID,
			&i.Name,
			&i.ImageID,
			&i.ListenCount,
			&i.MinutesListened,
			&i.ArtistID,
			&i.ArtistName,
			&i.AlbumID,
			&i.AlbumName,
			&i.Blacklisted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const truncateRollupTables = `-- name: TruncateRollupTables :exec
TRUNCATE daily_song_listens, clock_cells, user_listen_state, user_entity_first_listen, entity_global_stats
`

func (q *Queries) TruncateRollupTables(ctx context.Context) error {
	_, err := q.db.Exec(ctx, truncateRollupTables)
	return err
}

const upsertClockCells = `-- name: UpsertClockCells :exec
INSERT INTO clock_cells (user_id, day, hour, listen_count)
SELECT unnest($1::bigint[]),
       unnest($2::date[]),
       unnest($3::smallint[]),
       unnest($4::int[])
ON CONFLICT (user_id, day, hour) DO UPDATE SET
    listen_count = clock_cells.listen_count + excluded.listen_count
`

type UpsertClockCellsParams struct {
	UserIds      []int64       `json:"user_ids"`
	Days         []pgtype.Date `json:"days"`
	Hours        []int16       `json:"hours"`
	ListenCounts []int32       `json:"listen_counts"`
}

func (q *Queries) UpsertClockCells(ctx context.Context, arg UpsertClockCellsParams) error {
	_, err := q.db.Exec(ctx, upsertClockCells,
		arg.UserIds,
		arg.Days,
		arg.Hours,
		arg.ListenCounts,
	)
	return err
}

const upsertDailySongListens = `-- name: UpsertDailySongListens :exec
INSERT INTO daily_song_listens (user_id, song_id, day, listen_count, played_ms)
SELECT unnest($1::bigint[]),
       unnest($2::bigint[]),
       unnest($3::date[]),
       unnest($4::int[]),
       unnest($5::bigint[])
ON CONFLICT (user_id, song_id, day) DO UPDATE SET
    listen_count = daily_song_listens.listen_count + excluded.listen_count,
    played_ms = daily_song_listens.played_ms + excluded.played_ms
`

type UpsertDailySongListensParams struct {
	UserIds      []int64       `json:"user_ids"`
	SongIds      []int64       `json:"song_ids"`
	Days         []pgtype.Date `json:"days"`
	ListenCounts []int32       `json:"listen_counts"`
	PlayedMs     []int64       `json:"played_ms"`
}

func (q *Queries) UpsertDailySongListens(ctx context.Context, arg UpsertDailySongListensParams) error {
	_, err := q.db.Exec(ctx, upsertDailySongListens,
		arg.UserIds,
		arg.SongIds,
		arg.Days,
		arg.ListenCounts,
		arg.PlayedMs,
	)
	return err
}

const upsertEntityGlobalPlays = `-- name: UpsertEntityGlobalPlays :exec
INSERT INTO entity_global_stats (entity_type, entity_id, plays, played_ms, first_listened_at)
SELECT unnest($1::text[])::entity_type,
       unnest($2::bigint[]),
       unnest($3::int[]),
       unnest($4::bigint[]),
       unnest($5::timestamptz[])
ON CONFLICT (entity_type, entity_id) DO UPDATE SET
    plays = entity_global_stats.plays + excluded.plays,
    played_ms = entity_global_stats.played_ms + excluded.played_ms,
    first_listened_at = LEAST(entity_global_stats.first_listened_at, excluded.first_listened_at)
`

type UpsertEntityGlobalPlaysParams struct {
	EntityTypes []string             `json:"entity_types"`
	EntityIds   []int64              `json:"entity_ids"`
	Plays       []int32              `json:"plays"`
	PlayedMs    []int64              `json:"played_ms"`
	FirstAts    []pgtype.Timestamptz `json:"first_ats"`
}

func (q *Queries) UpsertEntityGlobalPlays(ctx context.Context, arg UpsertEntityGlobalPlaysParams) error {
	_, err := q.db.Exec(ctx, upsertEntityGlobalPlays,
		arg.EntityTypes,
		arg.EntityIds,
		arg.Plays,
		arg.PlayedMs,
		arg.FirstAts,
	)
	return err
}

const upsertUserListenStates = `-- name: UpsertUserListenStates :exec
INSERT INTO user_listen_state (user_id, last_listened_at, current_streak, longest_streak)
SELECT unnest($1::bigint[]),
       unnest($2::timestamptz[]),
       unnest($3::int[]),
       unnest($4::int[])
ON CONFLICT (user_id) DO UPDATE SET
    last_listened_at = excluded.last_listened_at,
    current_streak = excluded.current_streak,
    longest_streak = excluded.longest_streak
`

type UpsertUserListenStatesParams struct {
	UserIds         []int64              `json:"user_ids"`
	LastListenedAts []pgtype.Timestamptz `json:"last_listened_ats"`
	CurrentStreaks  []int32              `json:"current_streaks"`
	LongestStreaks  []int32              `json:"longest_streaks"`
}

func (q *Queries) UpsertUserListenStates(ctx context.Context, arg UpsertUserListenStatesParams) error {
	_, err := q.db.Exec(ctx, upsertUserListenStates,
		arg.UserIds,
		arg.LastListenedAts,
		arg.CurrentStreaks,
		arg.LongestStreaks,
	)
	return err
}
