// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rollup_unrecord.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const decrementClockCell = `-- name: DecrementClockCell :exec
UPDATE clock_cells SET listen_count = listen_count - 1
WHERE user_id = $1::bigint AND day = $2::date AND hour = $3::smallint
`

type DecrementClockCellParams struct {
	UserID int64       `json:"user_id"`
	Day    pgtype.Date `json:"day"`
	Hour   int16       `json:"hour"`
}

func (q *Queries) DecrementClockCell(ctx context.Context, arg DecrementClockCellParams) error {
	_, err := q.db.Exec(ctx, decrementClockCell, arg.UserID, arg.Day, arg.Hour)
	return err
}

const decrementDailySongListens = `-- name: DecrementDailySongListens :exec
UPDATE daily_song_listens SET listen_count = listen_count - 1, played_ms = GREATEST(played_ms - $1::bigint, 0)
WHERE user_id = $2::bigint AND song_id = $3::bigint AND day = $4::date
`

type DecrementDailySongListensParams struct {
	PlayedMs int64       `json:"played_ms"`
	UserID   int64       `json:"user_id"`
	SongID   int64       `json:"song_id"`
	Day      pgtype.Date `json:"day"`
}

func (q *Queries) DecrementDailySongListens(ctx context.Context, arg DecrementDailySongListensParams) error {
	_, err := q.db.Exec(ctx, decrementDailySongListens,
		arg.PlayedMs,
		arg.UserID,
		arg.SongID,
		arg.Day,
	)
	return err
}

const decrementEntityGlobalPlays = `-- name: DecrementEntityGlobalPlays :exec
UPDATE entity_global_stats SET plays = plays - 1, played_ms = GREATEST(played_ms - $1::bigint, 0)
WHERE entity_type = $2::entity_type AND entity_id = $3::bigint
`

type DecrementEntityGlobalPlaysParams struct {
	PlayedMs   int64      `json:"played_ms"`
	EntityType EntityType `json:"entity_type"`
	EntityID   int64      `json:"entity_id"`
}

func (q *Queries) DecrementEntityGlobalPlays(ctx context.Context, arg DecrementEntityGlobalPlaysParams) error {
	_, err := q.db.Exec(ctx, decrementEntityGlobalPlays, arg.PlayedMs, arg.EntityType, arg.EntityID)
	return err
}

const decrementEntityGlobalUniqueListeners = `-- name: DecrementEntityGlobalUniqueListeners :exec
UPDATE entity_global_stats SET unique_listeners = unique_listeners - 1
WHERE entity_type = $1::entity_type AND entity_id = $2::bigint
`

type DecrementEntityGlobalUniqueListenersParams struct {
	EntityType EntityType `json:"entity_type"`
	EntityID   int64      `json:"entity_id"`
}

func (q *Queries) DecrementEntityGlobalUniqueListeners(ctx context.Context, arg DecrementEntityGlobalUniqueListenersParams) error {
	_, err := q.db.Exec(ctx, decrementEntityGlobalUniqueListeners, arg.EntityType, arg.EntityID)
	return err
}

const deleteFirstListenForUserEntity = `-- name: DeleteFirstListenForUserEntity :exec
DELETE FROM user_entity_first_listen
WHERE user_id = $1::bigint AND entity_type = $2::entity_type AND entity_id = $3::bigint
`

type DeleteFirstListenForUserEntityParams struct {
	UserID     int64      `json:"user_id"`
	EntityType EntityType `json:"entity_type"`
	EntityID   int64      `json:"entity_id"`
}

func (q *Queries) DeleteFirstListenForUserEntity(ctx context.Context, arg DeleteFirstListenForUserEntityParams) error {
	_, err := q.db.Exec(ctx, deleteFirstListenForUserEntity, arg.UserID, arg.EntityType, arg.EntityID)
	return err
}

const getEntityGlobalFirstListenedAt = `-- name: GetEntityGlobalFirstListenedAt :one
SELECT first_listened_at FROM entity_global_stats
WHERE entity_type = $1::entity_type AND entity_id = $2::bigint
`

type GetEntityGlobalFirstListenedAtParams struct {
	EntityType EntityType `json:"entity_type"`
	EntityID   int64      `json:"entity_id"`
}

func (q *Queries) GetEntityGlobalFirstListenedAt(ctx context.Context, arg GetEntityGlobalFirstListenedAtParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getEntityGlobalFirstListenedAt, arg.EntityType, arg.EntityID)
	var first_listened_at pgtype.Timestamptz
	err := row.Scan(&first_listened_at)
	return first_listened_at, err
}

const getFirstListenForUserEntity = `-- name: GetFirstListenForUserEntity :one
SELECT first_at FROM user_entity_first_listen
WHERE user_id = $1::bigint AND entity_type = $2::entity_type AND entity_id = $3::bigint
`

type GetFirstListenForUserEntityParams struct {
	UserID     int64      `json:"user_id"`
	EntityType EntityType `json:"entity_type"`
	EntityID   int64      `json:"entity_id"`
}

func (q *Queries) GetFirstListenForUserEntity(ctx context.Context, arg GetFirstListenForUserEntityParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getFirstListenForUserEntity, arg.UserID, arg.EntityType, arg.EntityID)
	var first_at pgtype.Timestamptz
	err := row.Scan(&first_at)
	return first_at, err
}

const minEligibleListenedAtForAlbum = `-- name: MinEligibleListenedAtForAlbum :one
SELECT min(l.listened_at)::timestamptz FROM listens l JOIN songs s ON s.id = l.song_id JOIN song_albums sa ON sa.song_id = l.song_id
WHERE sa.album_id = $1::bigint
  AND ($2::bigint IS NULL OR l.user_id = $2::bigint)
  AND (s.duration_ms IS NULL OR s.duration_ms <= 0
       OR coalesce(l.duration_played_ms, s.duration_ms, 0) * 2 >= s.duration_ms
       OR coalesce(l.duration_played_ms, s.duration_ms, 0) >= 240000)
`

type MinEligibleListenedAtForAlbumParams struct {
	AlbumID int64  `json:"album_id"`
	UserID  *int64 `json:"user_id"`
}

func (q *Queries) MinEligibleListenedAtForAlbum(ctx context.Context, arg MinEligibleListenedAtForAlbumParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, minEligibleListenedAtForAlbum, arg.AlbumID, arg.UserID)
	var column_1 pgtype.Timestamptz
	err := row.Scan(&column_1)
	return column_1, err
}

const minEligibleListenedAtForArtist = `-- name: MinEligibleListenedAtForArtist :one
SELECT min(l.listened_at)::timestamptz FROM listens l JOIN songs s ON s.id = l.song_id JOIN song_artists sar ON sar.song_id = l.song_id
WHERE sar.artist_id = $1::bigint
  AND ($2::bigint IS NULL OR l.user_id = $2::bigint)
  AND (s.duration_ms IS NULL OR s.duration_ms <= 0
       OR coalesce(l.duration_played_ms, s.duration_ms, 0) * 2 >= s.duration_ms
       OR coalesce(l.duration_played_ms, s.duration_ms, 0) >= 240000)
`

type MinEligibleListenedAtForArtistParams struct {
	ArtistID int64  `json:"artist_id"`
	UserID   *int64 `json:"user_id"`
}

func (q *Queries) MinEligibleListenedAtForArtist(ctx context.Context, arg MinEligibleListenedAtForArtistParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, minEligibleListenedAtForArtist, arg.ArtistID, arg.UserID)
	var column_1 pgtype.Timestamptz
	err := row.Scan(&column_1)
	return column_1, err
}

const minEligibleListenedAtForSong = `-- name: MinEligibleListenedAtForSong :one
SELECT min(l.listened_at)::timestamptz FROM listens l JOIN songs s ON s.id = l.song_id
WHERE l.song_id = $1::bigint
  AND ($2::bigint IS NULL OR l.user_id = $2::bigint)
  AND (s.duration_ms IS NULL OR s.duration_ms <= 0
       OR coalesce(l.duration_played_ms, s.duration_ms, 0) * 2 >= s.duration_ms
       OR coalesce(l.duration_played_ms, s.duration_ms, 0) >= 240000)
`

type MinEligibleListenedAtForSongParams struct {
	SongID int64  `json:"song_id"`
	UserID *int64 `json:"user_id"`
}

func (q *Queries) MinEligibleListenedAtForSong(ctx context.Context, arg MinEligibleListenedAtForSongParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, minEligibleListenedAtForSong, arg.SongID, arg.UserID)
	var column_1 pgtype.Timestamptz
	err := row.Scan(&column_1)
	return column_1, err
}

const pruneEmptyClockCell = `-- name: PruneEmptyClockCell :exec
DELETE FROM clock_cells
WHERE user_id = $1::bigint AND day = $2::date AND hour = $3::smallint AND listen_count <= 0
`

type PruneEmptyClockCellParams struct {
	UserID int64       `json:"user_id"`
	Day    pgtype.Date `json:"day"`
	Hour   int16       `json:"hour"`
}

func (q *Queries) PruneEmptyClockCell(ctx context.Context, arg PruneEmptyClockCellParams) error {
	_, err := q.db.Exec(ctx, pruneEmptyClockCell, arg.UserID, arg.Day, arg.Hour)
	return err
}

const pruneEmptyDailySongListens = `-- name: PruneEmptyDailySongListens :exec
DELETE FROM daily_song_listens
WHERE user_id = $1::bigint AND song_id = $2::bigint AND day = $3::date AND listen_count <= 0
`

type PruneEmptyDailySongListensParams struct {
	UserID int64       `json:"user_id"`
	SongID int64       `json:"song_id"`
	Day    pgtype.Date `json:"day"`
}

func (q *Queries) PruneEmptyDailySongListens(ctx context.Context, arg PruneEmptyDailySongListensParams) error {
	_, err := q.db.Exec(ctx, pruneEmptyDailySongListens, arg.UserID, arg.SongID, arg.Day)
	return err
}

const pruneEmptyEntityGlobalStats = `-- name: PruneEmptyEntityGlobalStats :exec
DELETE FROM entity_global_stats
WHERE entity_type = $1::entity_type AND entity_id = $2::bigint AND plays <= 0
`

type PruneEmptyEntityGlobalStatsParams struct {
	EntityType EntityType `json:"entity_type"`
	EntityID   int64      `json:"entity_id"`
}

func (q *Queries) PruneEmptyEntityGlobalStats(ctx context.Context, arg PruneEmptyEntityGlobalStatsParams) error {
	_, err := q.db.Exec(ctx, pruneEmptyEntityGlobalStats, arg.EntityType, arg.EntityID)
	return err
}

const remainingUserAlbumPlays = `-- name: RemainingUserAlbumPlays :one
SELECT count(*)::bigint FROM listens l JOIN songs s ON s.id = l.song_id JOIN song_albums sa ON sa.song_id = l.song_id
WHERE l.user_id = $1::bigint AND sa.album_id = $2::bigint
  AND (s.duration_ms IS NULL OR s.duration_ms <= 0
       OR coalesce(l.duration_played_ms, s.duration_ms, 0) * 2 >= s.duration_ms
       OR coalesce(l.duration_played_ms, s.duration_ms, 0) >= 240000)
`

type RemainingUserAlbumPlaysParams struct {
	UserID  int64 `json:"user_id"`
	AlbumID int64 `json:"album_id"`
}

func (q *Queries) RemainingUserAlbumPlays(ctx context.Context, arg RemainingUserAlbumPlaysParams) (int64, error) {
	row := q.db.QueryRow(ctx, remainingUserAlbumPlays, arg.UserID, arg.AlbumID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const remainingUserArtistPlays = `-- name: RemainingUserArtistPlays :one
SELECT count(*)::bigint FROM listens l JOIN songs s ON s.id = l.song_id JOIN song_artists sar ON sar.song_id = l.song_id
WHERE l.user_id = $1::bigint AND sar.artist_id = $2::bigint
  AND (s.duration_ms IS NULL OR s.duration_ms <= 0
       OR coalesce(l.duration_played_ms, s.duration_ms, 0) * 2 >= s.duration_ms
       OR coalesce(l.duration_played_ms, s.duration_ms, 0) >= 240000)
`

type RemainingUserArtistPlaysParams struct {
	UserID   int64 `json:"user_id"`
	ArtistID int64 `json:"artist_id"`
}

func (q *Queries) RemainingUserArtistPlays(ctx context.Context, arg RemainingUserArtistPlaysParams) (int64, error) {
	row := q.db.QueryRow(ctx, remainingUserArtistPlays, arg.UserID, arg.ArtistID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const remainingUserSongPlays = `-- name: RemainingUserSongPlays :one
SELECT count(*)::bigint FROM listens l JOIN songs s ON s.id = l.song_id
WHERE l.user_id = $1::bigint AND l.song_id = $2::bigint
  AND (s.duration_ms IS NULL OR s.duration_ms <= 0
       OR coalesce(l.duration_played_ms, s.duration_ms, 0) * 2 >= s.duration_ms
       OR coalesce(l.duration_played_ms, s.duration_ms, 0) >= 240000)
`

type RemainingUserSongPlaysParams struct {
	UserID int64 `json:"user_id"`
	SongID int64 `json:"song_id"`
}

func (q *Queries) RemainingUserSongPlays(ctx context.Context, arg RemainingUserSongPlaysParams) (int64, error) {
	row := q.db.QueryRow(ctx, remainingUserSongPlays, arg.UserID, arg.SongID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const setEntityGlobalFirstListenedAt = `-- name: SetEntityGlobalFirstListenedAt :exec
UPDATE entity_global_stats SET first_listened_at = $1::timestamptz
WHERE entity_type = $2::entity_type AND entity_id = $3::bigint
`

type SetEntityGlobalFirstListenedAtParams struct {
	FirstListenedAt pgtype.Timestamptz `json:"first_listened_at"`
	EntityType      EntityType         `json:"entity_type"`
	EntityID        int64              `json:"entity_id"`
}

func (q *Queries) SetEntityGlobalFirstListenedAt(ctx context.Context, arg SetEntityGlobalFirstListenedAtParams) error {
	_, err := q.db.Exec(ctx, setEntityGlobalFirstListenedAt, arg.FirstListenedAt, arg.EntityType, arg.EntityID)
	return err
}

const setFirstListenForUserEntity = `-- name: SetFirstListenForUserEntity :exec
UPDATE user_entity_first_listen SET first_at = $1::timestamptz
WHERE user_id = $2::bigint AND entity_type = $3::entity_type AND entity_id = $4::bigint
`

type SetFirstListenForUserEntityParams struct {
	FirstAt    pgtype.Timestamptz `json:"first_at"`
	UserID     int64              `json:"user_id"`
	EntityType EntityType         `json:"entity_type"`
	EntityID   int64              `json:"entity_id"`
}

func (q *Queries) SetFirstListenForUserEntity(ctx context.Context, arg SetFirstListenForUserEntityParams) error {
	_, err := q.db.Exec(ctx, setFirstListenForUserEntity,
		arg.FirstAt,
		arg.UserID,
		arg.EntityType,
		arg.EntityID,
	)
	return err
}
