// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: server_state.sql

package db

import (
	"context"
)

const getServerState = `-- name: GetServerState :one
SELECT clean_shutdown FROM server_state WHERE id = true
`

func (q *Queries) GetServerState(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, getServerState)
	var clean_shutdown bool
	err := row.Scan(&clean_shutdown)
	return clean_shutdown, err
}

const markServerRunning = `-- name: MarkServerRunning :exec
UPDATE server_state SET clean_shutdown = false WHERE id = true
`

func (q *Queries) MarkServerRunning(ctx context.Context) error {
	_, err := q.db.Exec(ctx, markServerRunning)
	return err
}

const markServerShutdownClean = `-- name: MarkServerShutdownClean :exec
UPDATE server_state SET clean_shutdown = true WHERE id = true
`

func (q *Queries) MarkServerShutdownClean(ctx context.Context) error {
	_, err := q.db.Exec(ctx, markServerShutdownClean)
	return err
}
