// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, token_hash, expires_at) VALUES ($1, $2, $3) RETURNING id, user_id, token_hash, expires_at, created_at
`

type CreateSessionParams struct {
	UserID    int64              `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deleteOtherSessionsForUser = `-- name: DeleteOtherSessionsForUser :exec
DELETE FROM sessions WHERE user_id = $1 AND token_hash != $2
`

type DeleteOtherSessionsForUserParams struct {
	UserID    int64  `json:"user_id"`
	TokenHash string `json:"token_hash"`
}

func (q *Queries) DeleteOtherSessionsForUser(ctx context.Context, arg DeleteOtherSessionsForUserParams) error {
	_, err := q.db.Exec(ctx, deleteOtherSessionsForUser, arg.UserID, arg.TokenHash)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, deleteSession, tokenHash)
	return err
}

const getSessionUser = `-- name: GetSessionUser :one
SELECT users.id, users.username, users.password_hash, users.display_name, users.description, users.image_id, users.public, users.is_admin, users.created_at, sessions.expires_at AS session_expires_at FROM sessions
JOIN users ON users.id = sessions.user_id
WHERE sessions.token_hash = $1
`

type GetSessionUserRow struct {
	ID               int64              `json:"id"`
	Username         string             `json:"username"`
	PasswordHash     string             `json:"password_hash"`
	DisplayName      *string            `json:"display_name"`
	Description      *string            `json:"description"`
	ImageID          pgtype.UUID        `json:"image_id"`
	Public           bool               `json:"public"`
	IsAdmin          bool               `json:"is_admin"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	SessionExpiresAt pgtype.Timestamptz `json:"session_expires_at"`
}

func (q *Queries) GetSessionUser(ctx context.Context, tokenHash string) (GetSessionUserRow, error) {
	row := q.db.QueryRow(ctx, getSessionUser, tokenHash)
	var i GetSessionUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Description,
		&i.ImageID,
		&i.Public,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.SessionExpiresAt,
	)
	return i, err
}
