// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: songs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSong = `-- name: CreateSong :one
INSERT INTO songs (name, name_normalized, duration_ms) VALUES ($1, $2, $3) RETURNING id, name, name_normalized, duration_ms, image_id, pinned, created_at, updated_at
`

type CreateSongParams struct {
	Name           string `json:"name"`
	NameNormalized string `json:"name_normalized"`
	DurationMs     *int32 `json:"duration_ms"`
}

func (q *Queries) CreateSong(ctx context.Context, arg CreateSongParams) (Song, error) {
	row := q.db.QueryRow(ctx, createSong, arg.Name, arg.NameNormalized, arg.DurationMs)
	var i Song
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameNormalized,
		&i.DurationMs,
		&i.ImageID,
		&i.Pinned,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSong = `-- name: DeleteSong :execrows
DELETE FROM songs WHERE id = $1
`

func (q *Queries) DeleteSong(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSong, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSongArtists = `-- name: DeleteSongArtists :exec
DELETE FROM song_artists WHERE song_id = $1
`

func (q *Queries) DeleteSongArtists(ctx context.Context, songID int64) error {
	_, err := q.db.Exec(ctx, deleteSongArtists, songID)
	return err
}

const findSongByExactName = `-- name: FindSongByExactName :one
SELECT id, name, name_normalized, duration_ms, image_id, pinned, created_at, updated_at FROM songs WHERE name = $1 OR name_normalized = $1 LIMIT 1
`

func (q *Queries) FindSongByExactName(ctx context.Context, name string) (Song, error) {
	row := q.db.QueryRow(ctx, findSongByExactName, name)
	var i Song
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameNormalized,
		&i.DurationMs,
		&i.ImageID,
		&i.Pinned,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findSongByExactNameForArtists = `-- name: FindSongByExactNameForArtists :one
SELECT s.id, s.name, s.name_normalized, s.duration_ms, s.image_id, s.pinned, s.created_at, s.updated_at FROM songs s
JOIN song_artists sa ON sa.song_id = s.id
WHERE (s.name = $1::text OR s.name_normalized = $1::text) AND sa.artist_id = ANY($2::bigint[])
LIMIT 1
`

type FindSongByExactNameForArtistsParams struct {
	Name      string  `json:"name"`
	ArtistIds []int64 `json:"artist_ids"`
}

func (q *Queries) FindSongByExactNameForArtists(ctx context.Context, arg FindSongByExactNameForArtistsParams) (Song, error) {
	row := q.db.QueryRow(ctx, findSongByExactNameForArtists, arg.Name, arg.ArtistIds)
	var i Song
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameNormalized,
		&i.DurationMs,
		&i.ImageID,
		&i.Pinned,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findSongByExactNameForArtistsAndAlbum = `-- name: FindSongByExactNameForArtistsAndAlbum :one
SELECT s.id, s.name, s.name_normalized, s.duration_ms, s.image_id, s.pinned, s.created_at, s.updated_at FROM songs s
JOIN song_artists sa ON sa.song_id = s.id
JOIN song_albums sal ON sal.song_id = s.id
WHERE (s.name = $1::text OR s.name_normalized = $1::text)
  AND sa.artist_id = ANY($2::bigint[])
  AND sal.album_id = $3::bigint
LIMIT 1
`

type FindSongByExactNameForArtistsAndAlbumParams struct {
	Name      string  `json:"name"`
	ArtistIds []int64 `json:"artist_ids"`
	AlbumID   int64   `json:"album_id"`
}

func (q *Queries) FindSongByExactNameForArtistsAndAlbum(ctx context.Context, arg FindSongByExactNameForArtistsAndAlbumParams) (Song, error) {
	row := q.db.QueryRow(ctx, findSongByExactNameForArtistsAndAlbum, arg.Name, arg.ArtistIds, arg.AlbumID)
	var i Song
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameNormalized,
		&i.DurationMs,
		&i.ImageID,
		&i.Pinned,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findSongBySource = `-- name: FindSongBySource :one
SELECT s.id, s.name, s.name_normalized, s.duration_ms, s.image_id, s.pinned, s.created_at, s.updated_at FROM songs s
JOIN sources src ON src.entity_type = 'song' AND src.entity_id = s.id
WHERE src.source_type = $1 AND src.extracted_id = $2
`

type FindSongBySourceParams struct {
	SourceType  string  `json:"source_type"`
	ExtractedID *string `json:"extracted_id"`
}

func (q *Queries) FindSongBySource(ctx context.Context, arg FindSongBySourceParams) (Song, error) {
	row := q.db.QueryRow(ctx, findSongBySource, arg.SourceType, arg.ExtractedID)
	var i Song
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameNormalized,
		&i.DurationMs,
		&i.ImageID,
		&i.Pinned,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAlbumForSong = `-- name: GetAlbumForSong :one
SELECT al.id, al.name, al.name_normalized, al.release_date, al.description, al.image_id, al.pinned, al.created_at, al.updated_at, sal.track_number FROM albums al
JOIN song_albums sal ON sal.album_id = al.id
WHERE sal.song_id = $1
LIMIT 1
`

type GetAlbumForSongRow struct {
	ID             int64              `json:"id"`
	Name           string             `json:"name"`
	NameNormalized string             `json:"name_normalized"`
	ReleaseDate    pgtype.Date        `json:"release_date"`
	Description    *string            `json:"description"`
	ImageID        pgtype.UUID        `json:"image_id"`
	Pinned         bool               `json:"pinned"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	TrackNumber    *int32             `json:"track_number"`
}

func (q *Queries) GetAlbumForSong(ctx context.Context, songID int64) (GetAlbumForSongRow, error) {
	row := q.db.QueryRow(ctx, getAlbumForSong, songID)
	var i GetAlbumForSongRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameNormalized,
		&i.ReleaseDate,
		&i.Description,
		&i.ImageID,
		&i.Pinned,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TrackNumber,
	)
	return i, err
}

const getSongByID = `-- name: GetSongByID :one
SELECT id, name, name_normalized, duration_ms, image_id, pinned, created_at, updated_at FROM songs WHERE id = $1
`

func (q *Queries) GetSongByID(ctx context.Context, id int64) (Song, error) {
	row := q.db.QueryRow(ctx, getSongByID, id)
	var i Song
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameNormalized,
		&i.DurationMs,
		&i.ImageID,
		&i.Pinned,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSongsByIDs = `-- name: GetSongsByIDs :many
SELECT id, name, name_normalized, duration_ms, image_id, pinned, created_at, updated_at FROM songs WHERE id = ANY($1::bigint[])
`

func (q *Queries) GetSongsByIDs(ctx context.Context, ids []int64) ([]Song, error) {
	rows, err := q.db.Query(ctx, getSongsByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Song
	for rows.Next() {
		var i Song
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NameNormalized,
			&i.DurationMs,
			&i.ImageID,
			&i.Pinned,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const linkSongAlbum = `-- name: LinkSongAlbum :exec
INSERT INTO song_albums (song_id, album_id, track_number) VALUES ($1, $2, $3)
ON CONFLICT (song_id, album_id) DO UPDATE SET track_number = COALESCE(song_albums.track_number, excluded.track_number)
`

type LinkSongAlbumParams struct {
	SongID      int64  `json:"song_id"`
	AlbumID     int64  `json:"album_id"`
	TrackNumber *int32 `json:"track_number"`
}

func (q *Queries) LinkSongAlbum(ctx context.Context, arg LinkSongAlbumParams) error {
	_, err := q.db.Exec(ctx, linkSongAlbum, arg.SongID, arg.AlbumID, arg.TrackNumber)
	return err
}

const linkSongArtist = `-- name: LinkSongArtist :exec
INSERT INTO song_artists (song_id, artist_id, position) VALUES ($1, $2, $3)
ON CONFLICT (song_id, artist_id) DO UPDATE SET position = excluded.position
`

type LinkSongArtistParams struct {
	SongID   int64 `json:"song_id"`
	ArtistID int64 `json:"artist_id"`
	Position int16 `json:"position"`
}

func (q *Queries) LinkSongArtist(ctx context.Context, arg LinkSongArtistParams) error {
	_, err := q.db.Exec(ctx, linkSongArtist, arg.SongID, arg.ArtistID, arg.Position)
	return err
}

const listArtistsForSong = `-- name: ListArtistsForSong :many
SELECT a.id, a.name, a.name_normalized, a.description, a.image_id, a.pinned, a.created_at, a.updated_at FROM artists a
JOIN song_artists sa ON sa.artist_id = a.id
WHERE sa.song_id = $1
ORDER BY sa.position
`

func (q *Queries) ListArtistsForSong(ctx context.Context, songID int64) ([]Artist, error) {
	rows, err := q.db.Query(ctx, listArtistsForSong, songID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artist
	for rows.Next() {
		var i Artist
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NameNormalized,
			&i.Description,
			&i.ImageID,
			&i.Pinned,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSongArtists = `-- name: ListSongArtists :many
SELECT song_id, artist_id, position FROM song_artists WHERE song_id = $1 ORDER BY position
`

func (q *Queries) ListSongArtists(ctx context.Context, songID int64) ([]SongArtist, error) {
	rows, err := q.db.Query(ctx, listSongArtists, songID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SongArtist
	for rows.Next() {
		var i SongArtist
		if err := rows.Scan(&i.SongID, &i.ArtistID, &i.Position); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSongs = `-- name: ListSongs :many
SELECT id, name, name_normalized, duration_ms, image_id, pinned, created_at, updated_at FROM songs WHERE id > $1::bigint ORDER BY id LIMIT $2::int
`

type ListSongsParams struct {
	After   int64 `json:"after"`
	MaxRows int32 `json:"max_rows"`
}

func (q *Queries) ListSongs(ctx context.Context, arg ListSongsParams) ([]Song, error) {
	rows, err := q.db.Query(ctx, listSongs, arg.After, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Song
	for rows.Next() {
		var i Song
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NameNormalized,
			&i.DurationMs,
			&i.ImageID,
			&i.Pinned,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleSongs = `-- name: ListStaleSongs :many
SELECT id, name, name_normalized, duration_ms, image_id, pinned, created_at, updated_at FROM songs WHERE updated_at < $1::timestamptz AND NOT pinned ORDER BY updated_at LIMIT $2::int
`

type ListStaleSongsParams struct {
	Before  pgtype.Timestamptz `json:"before"`
	MaxRows int32              `json:"max_rows"`
}

func (q *Queries) ListStaleSongs(ctx context.Context, arg ListStaleSongsParams) ([]Song, error) {
	rows, err := q.db.Query(ctx, listStaleSongs, arg.Before, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Song
	for rows.Next() {
		var i Song
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NameNormalized,
			&i.DurationMs,
			&i.ImageID,
			&i.Pinned,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSongImage = `-- name: SetSongImage :one
UPDATE songs SET image_id = $2, pinned = TRUE, updated_at = now() WHERE id = $1 RETURNING id, name, name_normalized, duration_ms, image_id, pinned, created_at, updated_at
`

type SetSongImageParams struct {
	ID      int64       `json:"id"`
	ImageID pgtype.UUID `json:"image_id"`
}

func (q *Queries) SetSongImage(ctx context.Context, arg SetSongImageParams) (Song, error) {
	row := q.db.QueryRow(ctx, setSongImage, arg.ID, arg.ImageID)
	var i Song
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameNormalized,
		&i.DurationMs,
		&i.ImageID,
		&i.Pinned,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setSongPinned = `-- name: SetSongPinned :one
UPDATE songs SET pinned = $2 WHERE id = $1 RETURNING id, name, name_normalized, duration_ms, image_id, pinned, created_at, updated_at
`

type SetSongPinnedParams struct {
	ID     int64 `json:"id"`
	Pinned bool  `json:"pinned"`
}

func (q *Queries) SetSongPinned(ctx context.Context, arg SetSongPinnedParams) (Song, error) {
	row := q.db.QueryRow(ctx, setSongPinned, arg.ID, arg.Pinned)
	var i Song
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameNormalized,
		&i.DurationMs,
		&i.ImageID,
		&i.Pinned,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSong = `-- name: UpdateSong :one
UPDATE songs SET name = $2, name_normalized = $3, pinned = TRUE, updated_at = now() WHERE id = $1 RETURNING id, name, name_normalized, duration_ms, image_id, pinned, created_at, updated_at
`

type UpdateSongParams struct {
	ID             int64  `json:"id"`
	Name           string `json:"name"`
	NameNormalized string `json:"name_normalized"`
}

func (q *Queries) UpdateSong(ctx context.Context, arg UpdateSongParams) (Song, error) {
	row := q.db.QueryRow(ctx, updateSong, arg.ID, arg.Name, arg.NameNormalized)
	var i Song
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameNormalized,
		&i.DurationMs,
		&i.ImageID,
		&i.Pinned,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSongThumbnail = `-- name: UpdateSongThumbnail :exec
UPDATE songs SET image_id = $2, updated_at = now() WHERE id = $1 AND NOT pinned
`

type UpdateSongThumbnailParams struct {
	ID      int64       `json:"id"`
	ImageID pgtype.UUID `json:"image_id"`
}

func (q *Queries) UpdateSongThumbnail(ctx context.Context, arg UpdateSongThumbnailParams) error {
	_, err := q.db.Exec(ctx, updateSongThumbnail, arg.ID, arg.ImageID)
	return err
}
