// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sources.sql

package db

import (
	"context"
)

const getSourceEntityID = `-- name: GetSourceEntityID :one
SELECT entity_id FROM sources WHERE entity_type = $1 AND source_type = $2 AND extracted_id = $3
`

type GetSourceEntityIDParams struct {
	EntityType  EntityType `json:"entity_type"`
	SourceType  string     `json:"source_type"`
	ExtractedID *string    `json:"extracted_id"`
}

func (q *Queries) GetSourceEntityID(ctx context.Context, arg GetSourceEntityIDParams) (int64, error) {
	row := q.db.QueryRow(ctx, getSourceEntityID, arg.EntityType, arg.SourceType, arg.ExtractedID)
	var entity_id int64
	err := row.Scan(&entity_id)
	return entity_id, err
}

const insertSourceIfAbsent = `-- name: InsertSourceIfAbsent :one
INSERT INTO sources (entity_type, entity_id, source_type, raw_url, extracted_id, correlation_method, confidence)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (entity_type, source_type, extracted_id) WHERE extracted_id IS NOT NULL
DO UPDATE SET entity_id = sources.entity_id
RETURNING id, entity_type, entity_id, source_type, raw_url, extracted_id, correlation_method, confidence, created_at
`

type InsertSourceIfAbsentParams struct {
	EntityType        EntityType        `json:"entity_type"`
	EntityID          int64             `json:"entity_id"`
	SourceType        string            `json:"source_type"`
	RawUrl            *string           `json:"raw_url"`
	ExtractedID       *string           `json:"extracted_id"`
	CorrelationMethod CorrelationMethod `json:"correlation_method"`
	Confidence        *float32          `json:"confidence"`
}

func (q *Queries) InsertSourceIfAbsent(ctx context.Context, arg InsertSourceIfAbsentParams) (Source, error) {
	row := q.db.QueryRow(ctx, insertSourceIfAbsent,
		arg.EntityType,
		arg.EntityID,
		arg.SourceType,
		arg.RawUrl,
		arg.ExtractedID,
		arg.CorrelationMethod,
		arg.Confidence,
	)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.EntityType,
		&i.EntityID,
		&i.SourceType,
		&i.RawUrl,
		&i.ExtractedID,
		&i.CorrelationMethod,
		&i.Confidence,
		&i.CreatedAt,
	)
	return i, err
}

const listEntityIDsWithSourceType = `-- name: ListEntityIDsWithSourceType :many
SELECT DISTINCT entity_id FROM sources
WHERE entity_type = $1::entity_type
  AND source_type = $2::text
  AND entity_id = ANY($3::bigint[])
`

type ListEntityIDsWithSourceTypeParams struct {
	EntityType EntityType `json:"entity_type"`
	SourceType string     `json:"source_type"`
	EntityIds  []int64    `json:"entity_ids"`
}

func (q *Queries) ListEntityIDsWithSourceType(ctx context.Context, arg ListEntityIDsWithSourceTypeParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, listEntityIDsWithSourceType, arg.EntityType, arg.SourceType, arg.EntityIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var entity_id int64
		if err := rows.Scan(&entity_id); err != nil {
			return nil, err
		}
		items = append(items, entity_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSourcesForEntity = `-- name: ListSourcesForEntity :many
SELECT id, entity_type, entity_id, source_type, raw_url, extracted_id, correlation_method, confidence, created_at FROM sources WHERE entity_type = $1 AND entity_id = $2 ORDER BY created_at
`

type ListSourcesForEntityParams struct {
	EntityType EntityType `json:"entity_type"`
	EntityID   int64      `json:"entity_id"`
}

func (q *Queries) ListSourcesForEntity(ctx context.Context, arg ListSourcesForEntityParams) ([]Source, error) {
	rows, err := q.db.Query(ctx, listSourcesForEntity, arg.EntityType, arg.EntityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Source
	for rows.Next() {
		var i Source
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.EntityID,
			&i.SourceType,
			&i.RawUrl,
			&i.ExtractedID,
			&i.CorrelationMethod,
			&i.Confidence,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
