// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stats.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteStatsCache = `-- name: DeleteStatsCache :exec
TRUNCATE stats_cache
`

func (q *Queries) DeleteStatsCache(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteStatsCache)
	return err
}

const deleteStatsCacheForUser = `-- name: DeleteStatsCacheForUser :exec
DELETE FROM stats_cache WHERE user_id = $1::bigint OR user_id IS NULL
`

func (q *Queries) DeleteStatsCacheForUser(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteStatsCacheForUser, userID)
	return err
}

const entityUserSummary = `-- name: EntityUserSummary :one
SELECT count(*)::bigint AS plays,
       (coalesce(sum(coalesce(l.duration_played_ms, s.duration_ms, 0)), 0)::float8 / 60000.0)::float8 AS minutes_listened,
       min(l.listened_at)::timestamptz AS first_listened_at
FROM listens l
JOIN songs s ON s.id = l.song_id
WHERE l.user_id = $1::bigint
  AND (s.duration_ms IS NULL OR s.duration_ms <= 0
       OR coalesce(l.duration_played_ms, s.duration_ms, 0) * 2 >= s.duration_ms
       OR coalesce(l.duration_played_ms, s.duration_ms, 0) >= 240000)
  AND ($2::bigint IS NULL OR EXISTS (
        SELECT 1 FROM song_artists sar WHERE sar.song_id = l.song_id AND sar.artist_id = $2::bigint))
  AND ($3::bigint IS NULL OR EXISTS (
        SELECT 1 FROM song_albums sa2 WHERE sa2.song_id = l.song_id AND sa2.album_id = $3::bigint))
  AND ($4::bigint IS NULL OR l.song_id = $4::bigint)
`

type EntityUserSummaryParams struct {
	UserID   int64  `json:"user_id"`
	ArtistID *int64 `json:"artist_id"`
	AlbumID  *int64 `json:"album_id"`
	SongID   *int64 `json:"song_id"`
}

type EntityUserSummaryRow struct {
	Plays           int64              `json:"plays"`
	MinutesListened float64            `json:"minutes_listened"`
	FirstListenedAt pgtype.Timestamptz `json:"first_listened_at"`
}

// Stays a live query: one user's listens of one entity, small and bounded (see InterestHistory).
func (q *Queries) EntityUserSummary(ctx context.Context, arg EntityUserSummaryParams) (EntityUserSummaryRow, error) {
	row := q.db.QueryRow(ctx, entityUserSummary,
		arg.UserID,
		arg.ArtistID,
		arg.AlbumID,
		arg.SongID,
	)
	var i EntityUserSummaryRow
	err := row.Scan(&i.Plays, &i.MinutesListened, &i.FirstListenedAt)
	return i, err
}

const getStatsCache = `-- name: GetStatsCache :one
SELECT id, user_id, artist_id, album_id, song_id, resource, params, data, computed_at FROM stats_cache
WHERE user_id IS NOT DISTINCT FROM $1::bigint
  AND artist_id IS NOT DISTINCT FROM $2::bigint
  AND album_id IS NOT DISTINCT FROM $3::bigint
  AND song_id IS NOT DISTINCT FROM $4::bigint
  AND resource = $5::stats_resource
  AND params = $6::jsonb
`

type GetStatsCacheParams struct {
	UserID   *int64        `json:"user_id"`
	ArtistID *int64        `json:"artist_id"`
	AlbumID  *int64        `json:"album_id"`
	SongID   *int64        `json:"song_id"`
	Resource StatsResource `json:"resource"`
	Params   []byte        `json:"params"`
}

func (q *Queries) GetStatsCache(ctx context.Context, arg GetStatsCacheParams) (StatsCache, error) {
	row := q.db.QueryRow(ctx, getStatsCache,
		arg.UserID,
		arg.ArtistID,
		arg.AlbumID,
		arg.SongID,
		arg.Resource,
		arg.Params,
	)
	var i StatsCache
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ArtistID,
		&i.AlbumID,
		&i.SongID,
		&i.Resource,
		&i.Params,
		&i.Data,
		&i.ComputedAt,
	)
	return i, err
}

const interestHistory = `-- name: InterestHistory :many
SELECT l.listened_at
FROM listens l
JOIN songs s ON s.id = l.song_id
WHERE ($1::bigint IS NULL OR l.user_id = $1::bigint)
  AND (s.duration_ms IS NULL OR s.duration_ms <= 0
       OR coalesce(l.duration_played_ms, s.duration_ms, 0) * 2 >= s.duration_ms
       OR coalesce(l.duration_played_ms, s.duration_ms, 0) >= 240000)
  AND ($2::bigint IS NULL OR EXISTS (
        SELECT 1 FROM song_artists sar WHERE sar.song_id = l.song_id AND sar.artist_id = $2::bigint))
  AND ($3::bigint IS NULL OR EXISTS (
        SELECT 1 FROM song_albums sa2 WHERE sa2.song_id = l.song_id AND sa2.album_id = $3::bigint))
  AND ($4::bigint IS NULL OR l.song_id = $4::bigint)
ORDER BY l.listened_at
`

type InterestHistoryParams struct {
	UserID   *int64 `json:"user_id"`
	ArtistID *int64 `json:"artist_id"`
	AlbumID  *int64 `json:"album_id"`
	SongID   *int64 `json:"song_id"`
}

// Stays a live query: already scoped to one entity's own listens, small and bounded.
func (q *Queries) InterestHistory(ctx context.Context, arg InterestHistoryParams) ([]pgtype.Timestamptz, error) {
	rows, err := q.db.Query(ctx, interestHistory,
		arg.UserID,
		arg.ArtistID,
		arg.AlbumID,
		arg.SongID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.Timestamptz
	for rows.Next() {
		var listened_at pgtype.Timestamptz
		if err := rows.Scan(&listened_at); err != nil {
			return nil, err
		}
		items = append(items, listened_at)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStatsCache = `-- name: ListStatsCache :many
SELECT id, user_id, artist_id, album_id, song_id, resource, params, data, computed_at FROM stats_cache ORDER BY id
`

func (q *Queries) ListStatsCache(ctx context.Context) ([]StatsCache, error) {
	rows, err := q.db.Query(ctx, listStatsCache)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StatsCache
	for rows.Next() {
		var i StatsCache
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ArtistID,
			&i.AlbumID,
			&i.SongID,
			&i.Resource,
			&i.Params,
			&i.Data,
			&i.ComputedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneStaleStatsCache = `-- name: PruneStaleStatsCache :execrows
DELETE FROM stats_cache WHERE computed_at < $1::timestamptz
`

func (q *Queries) PruneStaleStatsCache(ctx context.Context, before pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, pruneStaleStatsCache, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const sourcesBreakdown = `-- name: SourcesBreakdown :many
WITH user_listens AS (
    SELECT l.id, l.user_id, l.song_id, l.listened_at, l.client, l.duration_played_ms, l.extra, l.created_at FROM listens l
    JOIN songs s ON s.id = l.song_id
    WHERE ($1::bigint IS NULL OR l.user_id = $1::bigint)
      AND l.listened_at >= $2::timestamptz
      AND l.listened_at < $3::timestamptz
      AND (s.duration_ms IS NULL OR s.duration_ms <= 0
           OR coalesce(l.duration_played_ms, s.duration_ms, 0) * 2 >= s.duration_ms
           OR coalesce(l.duration_played_ms, s.duration_ms, 0) >= 240000)
),
primary_source AS (
    SELECT song_id, source_type FROM (
        SELECT entity_id AS song_id, source_type,
               row_number() OVER (PARTITION BY entity_id ORDER BY (correlation_method = 'source_id') DESC, id) AS rn
        FROM sources WHERE entity_type = 'song'
    ) t WHERE rn = 1
)
SELECT coalesce(ps.source_type::text, 'unknown') AS source_type, count(*)::bigint AS listen_count
FROM user_listens ul
LEFT JOIN primary_source ps ON ps.song_id = ul.song_id
GROUP BY coalesce(ps.source_type::text, 'unknown')
ORDER BY count(*) DESC
`

type SourcesBreakdownParams struct {
	UserID   *int64             `json:"user_id"`
	FromTime pgtype.Timestamptz `json:"from_time"`
	ToTime   pgtype.Timestamptz `json:"to_time"`
}

type SourcesBreakdownRow struct {
	SourceType  interface{} `json:"source_type"`
	ListenCount int64       `json:"listen_count"`
}

// Stays a live query (not rolled up): source_type can change on re-correlation, so a
// rollup snapshot would go stale independent of new listens.
func (q *Queries) SourcesBreakdown(ctx context.Context, arg SourcesBreakdownParams) ([]SourcesBreakdownRow, error) {
	rows, err := q.db.Query(ctx, sourcesBreakdown, arg.UserID, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SourcesBreakdownRow
	for rows.Next() {
		var i SourcesBreakdownRow
		if err := rows.Scan(&i.SourceType, &i.ListenCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertStatsCache = `-- name: UpsertStatsCache :one
INSERT INTO stats_cache (user_id, artist_id, album_id, song_id, resource, params, data)
VALUES ($1::bigint, $2::bigint, $3::bigint, $4::bigint,
        $5::stats_resource, $6::jsonb, $7::jsonb)
ON CONFLICT (user_id, artist_id, album_id, song_id, resource, params)
DO UPDATE SET data = excluded.data, computed_at = now()
RETURNING id, user_id, artist_id, album_id, song_id, resource, params, data, computed_at
`

type UpsertStatsCacheParams struct {
	UserID   *int64        `json:"user_id"`
	ArtistID *int64        `json:"artist_id"`
	AlbumID  *int64        `json:"album_id"`
	SongID   *int64        `json:"song_id"`
	Resource StatsResource `json:"resource"`
	Params   []byte        `json:"params"`
	Data     []byte        `json:"data"`
}

func (q *Queries) UpsertStatsCache(ctx context.Context, arg UpsertStatsCacheParams) (StatsCache, error) {
	row := q.db.QueryRow(ctx, upsertStatsCache,
		arg.UserID,
		arg.ArtistID,
		arg.AlbumID,
		arg.SongID,
		arg.Resource,
		arg.Params,
		arg.Data,
	)
	var i StatsCache
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ArtistID,
		&i.AlbumID,
		&i.SongID,
		&i.Resource,
		&i.Params,
		&i.Data,
		&i.ComputedAt,
	)
	return i, err
}
