// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: trigram.sql

package db

import (
	"context"
)

const trigramMatchAlbumsByNormalized = `-- name: TrigramMatchAlbumsByNormalized :many
SELECT id, similarity(name_normalized, $1::text)::float8 AS sim FROM albums
WHERE name_normalized % $1::text
ORDER BY sim DESC LIMIT $2::int
`

type TrigramMatchAlbumsByNormalizedParams struct {
	Query   string `json:"query"`
	MaxRows int32  `json:"max_rows"`
}

type TrigramMatchAlbumsByNormalizedRow struct {
	ID  int64   `json:"id"`
	Sim float64 `json:"sim"`
}

func (q *Queries) TrigramMatchAlbumsByNormalized(ctx context.Context, arg TrigramMatchAlbumsByNormalizedParams) ([]TrigramMatchAlbumsByNormalizedRow, error) {
	rows, err := q.db.Query(ctx, trigramMatchAlbumsByNormalized, arg.Query, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TrigramMatchAlbumsByNormalizedRow
	for rows.Next() {
		var i TrigramMatchAlbumsByNormalizedRow
		if err := rows.Scan(&i.ID, &i.Sim); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const trigramMatchAlbumsByRomanized = `-- name: TrigramMatchAlbumsByRomanized :many
SELECT id, similarity(name_romanized, $1::text)::float8 AS sim FROM albums
WHERE name_romanized != '' AND name_romanized % $1::text
ORDER BY sim DESC LIMIT $2::int
`

type TrigramMatchAlbumsByRomanizedParams struct {
	Query   string `json:"query"`
	MaxRows int32  `json:"max_rows"`
}

type TrigramMatchAlbumsByRomanizedRow struct {
	ID  int64   `json:"id"`
	Sim float64 `json:"sim"`
}

func (q *Queries) TrigramMatchAlbumsByRomanized(ctx context.Context, arg TrigramMatchAlbumsByRomanizedParams) ([]TrigramMatchAlbumsByRomanizedRow, error) {
	rows, err := q.db.Query(ctx, trigramMatchAlbumsByRomanized, arg.Query, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TrigramMatchAlbumsByRomanizedRow
	for rows.Next() {
		var i TrigramMatchAlbumsByRomanizedRow
		if err := rows.Scan(&i.ID, &i.Sim); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const trigramMatchArtistsByNormalized = `-- name: TrigramMatchArtistsByNormalized :many
SELECT id, similarity(name_normalized, $1::text)::float8 AS sim FROM artists
WHERE name_normalized % $1::text
ORDER BY sim DESC LIMIT $2::int
`

type TrigramMatchArtistsByNormalizedParams struct {
	Query   string `json:"query"`
	MaxRows int32  `json:"max_rows"`
}

type TrigramMatchArtistsByNormalizedRow struct {
	ID  int64   `json:"id"`
	Sim float64 `json:"sim"`
}

func (q *Queries) TrigramMatchArtistsByNormalized(ctx context.Context, arg TrigramMatchArtistsByNormalizedParams) ([]TrigramMatchArtistsByNormalizedRow, error) {
	rows, err := q.db.Query(ctx, trigramMatchArtistsByNormalized, arg.Query, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TrigramMatchArtistsByNormalizedRow
	for rows.Next() {
		var i TrigramMatchArtistsByNormalizedRow
		if err := rows.Scan(&i.ID, &i.Sim); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const trigramMatchArtistsByRomanized = `-- name: TrigramMatchArtistsByRomanized :many
SELECT id, similarity(name_romanized, $1::text)::float8 AS sim FROM artists
WHERE name_romanized != '' AND name_romanized % $1::text
ORDER BY sim DESC LIMIT $2::int
`

type TrigramMatchArtistsByRomanizedParams struct {
	Query   string `json:"query"`
	MaxRows int32  `json:"max_rows"`
}

type TrigramMatchArtistsByRomanizedRow struct {
	ID  int64   `json:"id"`
	Sim float64 `json:"sim"`
}

func (q *Queries) TrigramMatchArtistsByRomanized(ctx context.Context, arg TrigramMatchArtistsByRomanizedParams) ([]TrigramMatchArtistsByRomanizedRow, error) {
	rows, err := q.db.Query(ctx, trigramMatchArtistsByRomanized, arg.Query, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TrigramMatchArtistsByRomanizedRow
	for rows.Next() {
		var i TrigramMatchArtistsByRomanizedRow
		if err := rows.Scan(&i.ID, &i.Sim); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const trigramMatchSongsByNormalized = `-- name: TrigramMatchSongsByNormalized :many
SELECT id, similarity(name_normalized, $1::text)::float8 AS sim FROM songs
WHERE name_normalized % $1::text
ORDER BY sim DESC LIMIT $2::int
`

type TrigramMatchSongsByNormalizedParams struct {
	Query   string `json:"query"`
	MaxRows int32  `json:"max_rows"`
}

type TrigramMatchSongsByNormalizedRow struct {
	ID  int64   `json:"id"`
	Sim float64 `json:"sim"`
}

func (q *Queries) TrigramMatchSongsByNormalized(ctx context.Context, arg TrigramMatchSongsByNormalizedParams) ([]TrigramMatchSongsByNormalizedRow, error) {
	rows, err := q.db.Query(ctx, trigramMatchSongsByNormalized, arg.Query, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TrigramMatchSongsByNormalizedRow
	for rows.Next() {
		var i TrigramMatchSongsByNormalizedRow
		if err := rows.Scan(&i.ID, &i.Sim); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const trigramMatchSongsByRomanized = `-- name: TrigramMatchSongsByRomanized :many
SELECT id, similarity(name_romanized, $1::text)::float8 AS sim FROM songs
WHERE name_romanized != '' AND name_romanized % $1::text
ORDER BY sim DESC LIMIT $2::int
`

type TrigramMatchSongsByRomanizedParams struct {
	Query   string `json:"query"`
	MaxRows int32  `json:"max_rows"`
}

type TrigramMatchSongsByRomanizedRow struct {
	ID  int64   `json:"id"`
	Sim float64 `json:"sim"`
}

func (q *Queries) TrigramMatchSongsByRomanized(ctx context.Context, arg TrigramMatchSongsByRomanizedParams) ([]TrigramMatchSongsByRomanizedRow, error) {
	rows, err := q.db.Query(ctx, trigramMatchSongsByRomanized, arg.Query, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TrigramMatchSongsByRomanizedRow
	for rows.Next() {
		var i TrigramMatchSongsByRomanizedRow
		if err := rows.Scan(&i.ID, &i.Sim); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
