// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_settings.sql

package db

import (
	"context"
)

const getUserSettings = `-- name: GetUserSettings :one
SELECT user_id, settings FROM user_settings WHERE user_id = $1
`

func (q *Queries) GetUserSettings(ctx context.Context, userID int64) (UserSetting, error) {
	row := q.db.QueryRow(ctx, getUserSettings, userID)
	var i UserSetting
	err := row.Scan(&i.UserID, &i.Settings)
	return i, err
}

const upsertUserSettings = `-- name: UpsertUserSettings :one
INSERT INTO user_settings (user_id, settings) VALUES ($1, $2)
ON CONFLICT (user_id) DO UPDATE SET settings = excluded.settings
RETURNING user_id, settings
`

type UpsertUserSettingsParams struct {
	UserID   int64  `json:"user_id"`
	Settings []byte `json:"settings"`
}

func (q *Queries) UpsertUserSettings(ctx context.Context, arg UpsertUserSettingsParams) (UserSetting, error) {
	row := q.db.QueryRow(ctx, upsertUserSettings, arg.UserID, arg.Settings)
	var i UserSetting
	err := row.Scan(&i.UserID, &i.Settings)
	return i, err
}
