// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAdmins = `-- name: CountAdmins :one
SELECT count(*) FROM users WHERE is_admin = TRUE
`

func (q *Queries) CountAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAdminUser = `-- name: CreateAdminUser :one
INSERT INTO users (username, password_hash, is_admin) VALUES ($1, $2, TRUE) RETURNING id, username, password_hash, display_name, description, image_id, public, is_admin, created_at
`

type CreateAdminUserParams struct {
	Username     string `json:"username"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) CreateAdminUser(ctx context.Context, arg CreateAdminUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createAdminUser, arg.Username, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Description,
		&i.ImageID,
		&i.Public,
		&i.IsAdmin,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, password_hash) VALUES ($1, $2) RETURNING id, username, password_hash, display_name, description, image_id, public, is_admin, created_at
`

type CreateUserParams struct {
	Username     string `json:"username"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Description,
		&i.ImageID,
		&i.Public,
		&i.IsAdmin,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, password_hash, display_name, description, image_id, public, is_admin, created_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Description,
		&i.ImageID,
		&i.Public,
		&i.IsAdmin,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password_hash, display_name, description, image_id, public, is_admin, created_at FROM users WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Description,
		&i.ImageID,
		&i.Public,
		&i.IsAdmin,
		&i.CreatedAt,
	)
	return i, err
}

const getUsersByIDs = `-- name: GetUsersByIDs :many
SELECT id, username, password_hash, display_name, description, image_id, public, is_admin, created_at FROM users WHERE id = ANY($1::bigint[])
`

func (q *Queries) GetUsersByIDs(ctx context.Context, ids []int64) ([]User, error) {
	rows, err := q.db.Query(ctx, getUsersByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.PasswordHash,
			&i.DisplayName,
			&i.Description,
			&i.ImageID,
			&i.Public,
			&i.IsAdmin,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicUsers = `-- name: ListPublicUsers :many
SELECT id, username, password_hash, display_name, description, image_id, public, is_admin, created_at FROM users WHERE public AND id > $1::bigint ORDER BY id LIMIT $2::int
`

type ListPublicUsersParams struct {
	After   int64 `json:"after"`
	MaxRows int32 `json:"max_rows"`
}

func (q *Queries) ListPublicUsers(ctx context.Context, arg ListPublicUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listPublicUsers, arg.After, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.PasswordHash,
			&i.DisplayName,
			&i.Description,
			&i.ImageID,
			&i.Public,
			&i.IsAdmin,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserImage = `-- name: SetUserImage :one
UPDATE users SET image_id = $2 WHERE id = $1 RETURNING id, username, password_hash, display_name, description, image_id, public, is_admin, created_at
`

type SetUserImageParams struct {
	ID      int64       `json:"id"`
	ImageID pgtype.UUID `json:"image_id"`
}

func (q *Queries) SetUserImage(ctx context.Context, arg SetUserImageParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserImage, arg.ID, arg.ImageID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Description,
		&i.ImageID,
		&i.Public,
		&i.IsAdmin,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :one
UPDATE users SET password_hash = $2 WHERE id = $1 RETURNING id, username, password_hash, display_name, description, image_id, public, is_admin, created_at
`

type UpdateUserPasswordParams struct {
	ID           int64  `json:"id"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Description,
		&i.ImageID,
		&i.Public,
		&i.IsAdmin,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users SET display_name = $2, description = $3, public = $4 WHERE id = $1 RETURNING id, username, password_hash, display_name, description, image_id, public, is_admin, created_at
`

type UpdateUserProfileParams struct {
	ID          int64   `json:"id"`
	DisplayName *string `json:"display_name"`
	Description *string `json:"description"`
	Public      bool    `json:"public"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.ID,
		arg.DisplayName,
		arg.Description,
		arg.Public,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Description,
		&i.ImageID,
		&i.Public,
		&i.IsAdmin,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserUsername = `-- name: UpdateUserUsername :one
UPDATE users SET username = $2 WHERE id = $1 RETURNING id, username, password_hash, display_name, description, image_id, public, is_admin, created_at
`

type UpdateUserUsernameParams struct {
	ID       int64  `json:"id"`
	Username string `json:"username"`
}

func (q *Queries) UpdateUserUsername(ctx context.Context, arg UpdateUserUsernameParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserUsername, arg.ID, arg.Username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Description,
		&i.ImageID,
		&i.Public,
		&i.IsAdmin,
		&i.CreatedAt,
	)
	return i, err
}
